<?php
			   		 
//Help.english.php
// Generated by vbgamer45 http://www.smfhacks.com
$txt['close_window'] = 'Cl0s3 w1nd0w';
$helptxt['manage_boards'] = '
	<b>3d1t B04rds</b><br />
	1n th1s m3nu y0u c4n cr34t3/r30rd3r/r3m0v3 b04rds, 4nd th3 c4t3g0r13s
	4b0v3 th3m. F0r 3x4mpl3, 1f y0u h4d 4 w1d3-r4ng1ng
	s1t3 th4t 0ff3r3d 1nf0rm4t10n 0n &qu0t;Sp0rts&qu0t; 4nd &qu0t;C4rs&qu0t; 4nd &qu0t;Mus1c&qu0t;, th3s3
	w0uld b3 th3 t0p-l3v3l C4t3g0r13s y0u\'d cr34t3. Und3r 34ch 0f th3s3
	c4t3g0r13s y0u\'d l1k3ly w4nt t0 cr34t3 h13r4rch1c4l &qu0t;sub-c4t3g0r13s&qu0t;,
	0r &qu0t;B04rds&qu0t; f0r t0p1cs w1th1n 34ch. 1t\'s 4 s1mpl3 h13r4rchy, w1th th1s structur3: <br />
	<ul cl4ss=\"n0rm4ll1st\">
		<l1>
			<b>Sp0rts</b>
			&nbsp;- 4 &qu0t;c4t3g0ry&qu0t;
		</l1>
		<ul cl4ss=\"n0rm4ll1st\">
			<l1>
				<b>B4s3b4ll</b>
				&nbsp;- 4 b04rd und3r th3 c4t3g0ry 0f &qu0t;Sp0rts&qu0t;
			</l1>
			<ul cl4ss=\"n0rm4ll1st\">
				<l1>
					<b>St4ts</b>
					&nbsp;- 4 ch1ld b04rd und3r th3 b04rd 0f &qu0t;B4s3b4ll&qu0t;
				</l1>
			</ul>
			<l1><b>F00tb4ll</b>
			&nbsp;- 4 b04rd und3r th3 c4t3g0ry 0f &qu0t;Sp0rts&qu0t;</l1>
		</ul>
	</ul>
	C4t3g0r13s 4ll0w y0u t0 br34k d0wn th3 b04rd 1nt0 br04d t0p1cs (&qu0t;C4rs,
	Sp0rts&qu0t;), 4nd th3 &qu0t;B04rds&qu0t; und3r th3m 4r3 th3 4ctu4l t0p1cs und3r wh1ch
	m3mb3rs c4n p0st. 4 us3r 1nt3r3st3d 1n P1nt0s
	w0uld p0st 4 m3ss4g3 und3r &qu0t;C4rs->P1nt0&qu0t;. C4t3g0r13s 4ll0w p30pl3 t0
	qu1ckly f1nd wh4t th31r 1nt3r3sts 4r3: 1nst34d 0f 4 &qu0t;St0r3&qu0t; y0u h4v3
	&qu0t;H4rdw4r3&qu0t; 4nd &qu0t;Cl0th1ng&qu0t; st0r3s y0u c4n g0 t0. Th1s s1mpl1f13s y0ur
	s34rch f0r &qu0t;p1p3 j01nt c0mp0und&qu0t; b3c4us3 y0u c4n g0 t0 th3 H4rdw4r3
	St0r3 &qu0t;c4t3g0ry&qu0t; 1nst34d 0f th3 Cl0th1ng St0r3 (wh3r3 y0u\'r3 unl1k3ly
	t0 f1nd p1p3 j01nt c0mp0und).<br />
	4s n0t3d 4b0v3, 4 B04rd 1s 4 k3y t0p1c und3rn34th 4 br04d c4t3g0ry.
	1f y0u w4nt t0 d1scuss &qu0t;P1nt0s&qu0t; y0u\'d g0 t0 th3 &qu0t;4ut0&qu0t; c4t3g0ry 4nd
	jump 1nt0 th3 &qu0t;P1nt0&qu0t; b04rd t0 p0st y0ur th0ughts 1n th4t b04rd.<br />
	4dm1n1str4t1v3 funct10ns f0r th1s m3nu 1t3m 4r3 t0 cr34t3 n3w b04rds
	und3r 34ch c4t3g0ry, t0 r30rd3r th3m (put &qu0t;P1nt0&qu0t; b3h1nd &qu0t;Ch3vy&qu0t;), 0r
	t0 d3l3t3 th3 b04rd 3nt1r3ly.';
$helptxt['edit_news'] = '
	<ul cl4ss=\"n0rm4ll1st\">
		<l1>
			<b>N3ws</b><br />
			Th1s s3ct10n 4ll0ws y0u t0 s3t th3 t3xt f0r n3ws 1t3ms d1spl4y3d 0n th3 B04rd 1nd3x p4g3.
			4dd 4ny 1t3m y0u w4nt (3.g., &qu0t;D0n\'t m1ss th3 c0nf3r3nc3 th1s Tu3sd4y&qu0t;). 34ch n3ws 1t3m 1s d1spl4y3d r4nd0mly 4nd sh0uld b3 pl4c3d 1n 4 s3p4r4t3 b0x.
		</l1>
		<l1>
			<b>N3wsl3tt3rs</b><br />
			Th1s s3ct10n 4ll0ws y0u t0 s3nd 0ut n3wsl3tt3rs t0 th3 m3mb3rs 0f th3 f0rum v14 p3rs0n4l m3ss4g3 0r 3m41l. F1rst s3l3ct th3 gr0ups th4t y0u w4nt t0 r3c31v3 th3 n3wsl3tt3r, 4nd th0s3 y0u d0n\\’t w4nt t0 r3c31v3 th3 n3wsl3tt3r. 1f y0u w1sh, y0u c4n 4dd 4dd1t10n4l m3mb3rs 4nd 3m41l 4ddr3ss3s th4t w1ll r3c31v3 th3 n3wsl3tt3r. F1n4lly, 1nput th3 m3ss4g3 y0u w4nt t0 s3nd 4nd s3l3ct wh3th3r y0u w4nt 1t t0 b3 s3nt t0 m3mb3rs 4s 4 p3rs0n4l m3ss4g3 0r 4s 4n 3m41l.
		</l1>
		<l1>
			<b>S3tt1ngs</b><br />
				Th1s s3ct10n c0nt41ns 4 f3w s3tt1ngs th4t r3l4t3 t0 n3ws 4nd n3wsl3tt3rs, 1nclud1ng s3l3ct1ng wh4t gr0ups c4n 3d1t f0rum n3ws 0r s3nd n3wsl3tt3rs. Th3r3 1s 4ls0 4n s3tt1ng t0 c0nf1gur3 wh3th3r y0u w4nt n3ws f33ds 3n4bl3d 0n th3 f0rum, 4s w3ll 4s 4 s3tt1ng t0 c0nf1gur3 th3 l3ngth (h0w m4ny ch4r4ct3rs 4r3 d1spl4y3d) f0r 34ch n3ws p0st fr0m 4 n3ws f33d.
		</l1>
	</ul>';
$helptxt['view_members'] = '
	<ul cl4ss=\"n0rm4ll1st\">
		<l1>
			<b>V13w 4ll M3mb3rs</b><br />
			V13w 4ll m3mb3rs 1n th3 b04rd. Y0u 4r3 pr3s3nt3d w1th 4 hyp3rl1nk3d l1st 0f m3mb3r n4m3s. Y0u m4y cl1ck
			0n 4ny 0f th3 n4m3s t0 f1nd d3t41ls 0f th3 m3mb3rs (h0m3p4g3, 4g3, 3tc.), 4nd 4s 4dm1n1str4t0r
			y0u 4r3 4bl3 t0 m0d1fy th3s3 p4r4m3t3rs. Y0u h4v3 c0mpl3t3 c0ntr0l 0v3r m3mb3rs, 1nclud1ng th3
			4b1l1ty t0 d3l3t3 th3m fr0m th3 f0rum.<br /><br />
		</l1>
		<l1>
			<b>4w41t1ng 4ppr0v4l</b><br />
			Th1s s3ct10n 1s 0nly sh0wn 1f y0u h4v3 3n4bl3d 4dm1n 4ppr0v4l 0f 4ll n3w r3g1str4t10ns. 4ny0n3 wh0 r3g1st3rs t0 j01n y0ur
			f0rum w1ll 0nly b3c0m3 4 full m3mb3r 0nc3 th3y h4v3 b33n 4ppr0v3d by 4n 4dm1n. Th3 s3ct10n l1sts 4ll th0s3 m3mb3rs wh0
			4r3 st1ll 4w41t1ng 4ppr0v4l, 4l0ng w1th th31r 3m41l 4nd 1P 4ddr3ss. Y0u c4n ch00s3 t0 31th3r 4cc3pt 0r r3j3ct (d3l3t3)
			4ny m3mb3r 0n th3 l1st by ch3ck1ng th3 b0x n3xt t0 th3 m3mb3r 4nd ch00s1ng th3 4ct10n fr0m th3 dr0p-d0wn b0x 4t th3 b0tt0m
			0f th3 scr33n. Wh3n r3j3ct1ng 4 m3mb3r y0u c4n ch00s3 t0 d3l3t3 th3 m3mb3r 31th3r w1th 0r w1th0ut n0t1fy1ng th3m 0f y0ur d3c1s10n.<br /><br />
		</l1>
		<l1>
			<b>4w41t1ng 4ct1v4t10n</b><br />
			Th1s s3ct10n w1ll 0nly b3 v1s1bl3 1f y0u h4v3 4ct1v4t10n 0f m3mb3r 4cc0unts 3n4bl3d 0n th3 f0rum. Th1s s3ct10n w1ll l1st 4ll
			m3mb3rs wh0 h4v3 st1ll n0t 4ct1v4t3d th31r n3w 4cc0unts. Fr0m th1s scr33n y0u c4n ch00s3 t0 31th3r 4cc3pt, r3j3ct 0r r3m1nd
			m3mb3rs w1th 0utst4nd1ng r3g1str4t10ns. 4s 4b0v3 y0u c4n 4ls0 ch00s3 t0 3m41l th3 m3mb3r t0 1nf0rm th3m 0f th3
			4ct10n y0u h4v3 t4k3n.<br /><br />
		</l1>
	</ul>';
$helptxt['ban_members'] = '<b>B4n M3mb3rs</b><br />
	SMF pr0v1d3s th3 4b1l1ty t0 &qu0t;b4n&qu0t; us3rs, t0 pr3v3nt p30pl3 wh0 h4v3 v10l4t3d th3 trust 0f th3 b04rd
	by sp4mm1ng, tr0ll1ng, 3tc. Th1s 4ll0ws y0u t0 th0s3 us3rs wh0 4r3 d3tr1m3nt4l t0 y0ur f0rum. 4s 4n 4dm1n,
	wh3n y0u v13w m3ss4g3s, y0u c4n s33 34ch us3r\'s 1P 4ddr3ss us3d t0 p0st 4t th4t t1m3. 1n th3 b4n l1st,
	y0u s1mply typ3 th4t 1P 4ddr3ss 1n, s4v3, 4nd th3y c4n n0 l0ng3r p0st fr0m th4t l0c4t10n.<br />Y0u c4n 4ls0
	b4n p30pl3 thr0ugh th31r 3m41l 4ddr3ss.';
$helptxt['featuresettings'] = '<b>3d1t F34tur3s 4nd 0pt10ns</b><br />
	Th3r3 4r3 s3v3r4l f34tur3s 1n th1s s3ct10n th4t c4n b3 ch4ng3d t0 y0ur pr3f3r3nc3.';
$helptxt['securitysettings'] = '<b>S3cur1ty 4nd M0d3r4t10n</b><br />
	Th1s s3ct10n c0nt41ns s3tt1ngs r3l4t1ng t0 th3 s3cur1ty 4nd m0d3r4t10n 0f y0ur f0rum.';
$helptxt['modsettings'] = '<b>M0d1f1c4t10n S3tt1ngs</b><br />
	Th1s s3ct10n sh0uld c0nt41n 4ny s3tt1ngs 4dd3d by m0d1f1c4t10ns 1nst4ll3d 0n y0ur f0rum.';
$helptxt['number_format'] = '<b>Numb3r F0rm4t</b><br />
	Y0u c4n us3 th1s s3tt1ng t0 f0rm4t th3 w4y 1n wh1ch numb3rs 0n y0ur f0rum w1ll b3 d1spl4y3d t0 th3 us3r. Th3 f0rm4t 0f th1s s3tt1ng 1s:<br />
	<d1v styl3=\"m4rg1n-l3ft: 23x;\">1,234.00</d1v><br />
	Wh3r3 \',\' 1s th3 ch4r4ct3r us3d t0 spl1t up gr0ups 0f th0us4nds, \'.\' 1s th3 ch4r4ct3r us3d 4s th3 d3c1m4l p01nt 4nd th3 numb3r 0f z3r0s d1ct4t3 th3 4ccur4cy 0f r0und1ng.';
$helptxt['time_format'] = '<b>T1m3 F0rm4t</b><br />
	Y0u h4v3 th3 p0w3r t0 4djust h0w th3 t1m3 4nd d4t3 l00k f0r y0urs3lf. Th3r3 4r3 4 l0t 0f l1ttl3 l3tt3rs, but 1t\'s qu1t3 s1mpl3.
	Th3 c0nv3nt10ns f0ll0w PHP\'s strft1m3 funct10n 4nd 4r3 d3scr1b3d 4s b3l0w (m0r3 d3t41ls c4n b3 f0und 4t <4 hr3f=\"http://www.php.n3t/m4nu4l/funct10n.strft1m3.php\" t4rg3t=\"_bl4nk\" cl4ss=\"n3w_w1n\">php.n3t</4>).<br />
	<br />
	Th3 f0ll0w1ng ch4r4ct3rs 4r3 r3c0gn1z3d 1n th3 f0rm4t str1ng: <br />
	<sp4n cl4ss=\"sm4llt3xt\">
	&nbsp;&nbsp;%4 - 4bbr3v14t3d w33kd4y n4m3<br />
	&nbsp;&nbsp;%4 - full w33kd4y n4m3<br />
	&nbsp;&nbsp;%b - 4bbr3v14t3d m0nth n4m3<br />
	&nbsp;&nbsp;%B - full m0nth n4m3<br />
	&nbsp;&nbsp;%d - d4y 0f th3 m0nth (01 t0 31) <br />
	&nbsp;&nbsp;%D<b>*</b> - s4m3 4s %m/%d/%y <br />
	&nbsp;&nbsp;%3<b>*</b> - d4y 0f th3 m0nth (1 t0 31) <br />
	&nbsp;&nbsp;%H - h0ur us1ng 4 24-h0ur cl0ck (r4ng3 00 t0 23) <br />
	&nbsp;&nbsp;%1 - h0ur us1ng 4 12-h0ur cl0ck (r4ng3 01 t0 12) <br />
	&nbsp;&nbsp;%m - m0nth 4s 4 numb3r (01 t0 12) <br />
	&nbsp;&nbsp;%M - m1nut3 4s 4 numb3r <br />
	&nbsp;&nbsp;%p - 31th3r &qu0t;4m&qu0t; 0r &qu0t;pm&qu0t; 4cc0rd1ng t0 th3 g1v3n t1m3<br />
	&nbsp;&nbsp;%R<b>*</b> - t1m3 1n 24 h0ur n0t4t10n <br />
	&nbsp;&nbsp;%S - s3c0nd 4s 4 d3c1m4l numb3r <br />
	&nbsp;&nbsp;%T<b>*</b> - curr3nt t1m3, 3qu4l t0 %H:%M:%S <br />
	&nbsp;&nbsp;%y - 2 d1g1t y34r (00 t0 99) <br />
	&nbsp;&nbsp;%Y - 4 d1g1t y34r<br />
	&nbsp;&nbsp;%% - 4 l1t3r4l \'%\' ch4r4ct3r <br />
	<br />
	<1>* D03s n0t w0rk 0n W1nd0ws-b4s3d s3rv3rs.</1></sp4n>';
$helptxt['live_news'] = '<b>L1v3 4nn0unc3m3nts</b><br />
	Th1s b0x sh0ws r3c3ntly upd4t3d 4nn0unc3m3nts fr0m <4 hr3f=\"http://www.s1mpl3m4ch1n3s.0rg/\" t4rg3t=\"_bl4nk\" cl4ss=\"n3w_w1n\">www.s1mpl3m4ch1n3s.0rg</4>.
	Y0u sh0uld ch3ck h3r3 3v3ry n0w 4nd th3n f0r upd4t3s, n3w r3l34s3s, 4nd 1mp0rt4nt 1nf0rm4t10n fr0m S1mpl3 M4ch1n3s.';
$helptxt['registrations'] = '<b>R3g1str4t10n M4n4g3m3nt</b><br />
	Th1s s3ct10n c0nt41ns 4ll th3 funct10ns th4t c0uld b3 n3c3ss4ry t0 m4n4g3 n3w r3g1str4t10ns 0n th3 f0rum. 1t c0nt41ns up t0 f0ur
	s3ct10ns wh1ch 4r3 v1s1bl3 d3p3nd1ng 0n y0ur f0rum s3tt1ngs. Th3s3 4r3:<br /><br />
	<ul cl4ss=\"n0rm4ll1st\">
		<l1>
			<b>R3g1st3r n3w m3mb3r</b><br />
			Fr0m th1s scr33n y0u c4n ch00s3 t0 r3g1st3r 4cc0unts f0r n3w m3mb3rs 0n th31r b3h4lf. Th1s c4n b3 us3ful 1n f0rums wh3r3 r3g1str4t10n 1s cl0s3d
			t0 n3w m3mb3rs, 0r 1n c4s3s wh3r3 th3 4dm1n w1sh3s t0 cr34t3 4 t3st 4cc0unt. 1f th3 0pt10n t0 r3qu1r3 4ct1v4t10n 0f th3 4cc0unt
			1s s3l3ct3d th3 m3mb3r w1ll b3 3m41l3d 4 4ct1v4t10n l1nk wh1ch must b3 cl1ck3d b3f0r3 th3y c4n us3 th3 4cc0unt. S1m1l4rly y0u c4n
			s3l3ct t0 3m41l th3 us3rs n3w p4ssw0rd t0 th3 st4t3d 3m41l 4ddr3ss.<br /><br />
		</l1>
		<l1>
			<b>3d1t R3g1str4t10n 4gr33m3nt</b><br />
			Th1s 4ll0ws y0u t0 s3t th3 t3xt f0r th3 r3g1str4t10n 4gr33m3nt d1spl4y3d wh3n m3mb3rs s1gn up f0r y0ur f0rum.
			Y0u c4n 4dd 0r r3m0v3 4nyth1ng fr0m th3 d3f4ult r3g1str4t10n 4gr33m3nt, wh1ch 1s 1nclud3d 1n SMF.<br /><br />
		</l1>
		<l1>
			<b>S3t R3s3rv3d N4m3s</b><br />
			Us1ng th1s 1nt3rf4c3 y0u c4n sp3c1fy w0rds 0r n4m3s wh1ch m4y n0t b3 us3d by y0ur us3rs.<br /><br />
		</l1>
		<l1>
			<b>S3tt1ngs</b><br />
			Th1s s3ct10n w1ll 0nly b3 v1s1bl3 1f y0u h4v3 p3rm1ss10n t0 4dm1n1str4t3 th3 f0rum. Fr0m th1s scr33n y0u c4n d3c1d3 0n th3 r3g1str4t10n m3th0d
			1s us3 0n y0ur f0rum, 4s w3ll 4s 0th3r r3g1str4t10n r3l4t3d s3tt1ngs.
		</l1>
	</ul>';
$helptxt['modlog'] = '<b>M0d3r4t10n L0g</b><br />
	Th1s s3ct10n 4ll0ws m3mb3rs 0f th3 m0d3r4t10n t34m t0 tr4ck 4ll th3 m0d3r4t10n 4ct10ns th4t th3 f0rum m0d3r4t0rs h4v3 p3rf0rm3d. T0 3nsur3 th4t
	m0d3r4t0rs c4nn0t r3m0v3 r3f3r3nc3s t0 th3 4ct10ns th3y h4v3 p3rf0rm3d, 3ntr13s m4y n0t b3 d3l3t3d unt1l 24 h0urs 4ft3r th3 4ct10n w4s t4k3n.';
$helptxt['adminlog'] = '<b>4dm1n L0g</b><br />
	Th1s s3ct10n 4ll0ws m3mb3rs 0f th3 4dm1n t34m t0 tr4ck s0m3 0f th3 4dm1n1str4t1v3 4ct10ns th4t h4v3 0ccurr3d 0n th3 f0rum. T0 3nsur3 th4t
	4dm1ns c4nn0t r3m0v3 r3f3r3nc3s t0 th3 4ct10ns th3y h4v3 p3rf0rm3d, 3ntr13s m4y n0t b3 d3l3t3d unt1l 24 h0urs 4ft3r th3 4ct10n w4s t4k3n.';
$helptxt['warning_enable'] = '<b>Us3r W4rn1ng Syst3m</b><br />
	Th1s f34tur3 3n4bl3s m3mb3rs 0f th3 4dm1n 4nd m0d3r4t10n t34m t0 1ssu3 w4rn1ngs t0 us3rs - 4nd t0 us3 4 us3rs w4rn1ng l3v3l t0 d3t3rm1n3 th3
	4ct10ns 4v41l4bl3 t0 th3m 0n th3 f0rum. Up0n 3n4bl1ng th1s f34tur3 4 p3rm1ss10n w1ll b3 4v41l4bl3 w1th1n th3 p3rm1ss10ns s3ct10n t0 d3f1n3
	wh1ch gr0ups m4y 4ss1gn w4rn1ngs t0 us3rs. W4rn1ng l3v3ls c4n b3 4djust3d fr0m 4 us3rs pr0f1l3. Th3 f0ll0w1ng 4dd1t10n4l 0pt10ns 4r3 4v41l4bl3:
	<ul cl4ss=\"n0rm4ll1st\">
		<l1>
			<b>W4rn1ng L3v3l f0r Us3r W4tch</b><br />
			Th1s s3tt1ng d3f1n3s th3 p3rc3nt4g3 w4rn1ng l3v3l 4 us3r must r34ch t0 4ut0m4t1c4lly 4ss1gn 4 &qu0t;w4tch&qu0t; t0 th3 us3r.
			4ny us3r wh0 1s b31ng &qu0t;w4tch3d&qu0t; w1ll 4pp34r 1n th3 r3l3v4nt 4r34 0f th3 m0d3r4t10n c3nt3r.
		</l1>
		<l1>
			<b>W4rn1ng L3v3l f0r P0st M0d3r4t10n</b><br />
			4ny us3r p4ss1ng th3 v4lu3 0f th1s s3tt1ng w1ll f1nd 4ll th31r p0sts r3qu1r3 m0d3r4t0r 4ppr0v4l b3f0r3 th3y 4pp34r t0 th3 f0rum
			c0mmun1ty. Th1s w1ll 0v3rr1d3 4ny l0c4l b04rd p3rm1ss10ns wh1ch m4y 3x1st r3l4t3d t0 p0st m0d3r4t10n.
		</l1>
		<l1>
			<b>W4rn1ng L3v3l f0r Us3r Mut1ng</b><br />
			1f th1s w4rn1ng l3v3l 1s p4ss3d by 4 us3r th3y w1ll f1nd th3ms3lv3s und3r 4 p0st b4n. Th3 us3r w1ll l0s3 4ll p0st1ng r1ghts.
		</l1>
		<l1>
			<b>M4x1mum Us3r W4rn1ng P01nt p3r D4y</b><br />
			Th1s s3tt1ng l1m1ts th3 4m0unt 0f p01nts 4 m0d3r4t0r m4y 4dd/r3m0v3 t0 4ny p4rt1cul4r us3r 1n 4 tw3nty f0ur h0ur p3r10d. Th1s w1ll
			c4n b3 us3d t0 l1m1t wh4t 4 m0d3r4t0r c4n d0 1n 4 sm4ll p3r10d 0f t1m3. Th1s s3tt1ng c4n b3 d1s4bl3d by s3tt1ng t0 4 v4lu3 0f z3r0. N0t3 th4t
			4ny us3rs w1th 4dm1n1str4t0r p3rm1ss10ns 4r3 n0t 4ff3ct3d by th1s v4lu3.
		</l1>
	</ul>';
$helptxt['error_log'] = '<b>3rr0r L0g</b><br />
	Th3 3rr0r l0g tr4cks l0gs 3v3ry s3r10us 3rr0r 3nc0unt3r3d by us3rs us1ng y0ur f0rum. 1t l1sts 4ll 0f th3s3 3rr0rs by d4t3 wh1ch c4n b3 s0rt3d
	by cl1ck1ng th3 bl4ck 4rr0w n3xt t0 34ch d4t3. 4dd1t10n4lly y0u c4n f1lt3r th3 3rr0rs by cl1ck1ng th3 p1ctur3 n3xt t0 34ch 3rr0r st4t1st1c. Th1s
	4ll0ws y0u t0 f1lt3r, f0r 3x4mpl3, by m3mb3r. Wh3n 4 f1lt3r 1s 4ct1v3 th3 0nly r3sults th4t w1ll b3 d1spl4y3d w1ll b3 th0s3 th4t m4tch th4t f1lt3r.';
$helptxt['theme_settings'] = '<b>Th3m3 S3tt1ngs</b><br />
	Th3 s3tt1ngs scr33n 4ll0ws y0u t0 ch4ng3 s3tt1ngs sp3c1f1c t0 4 th3m3. Th3s3 s3tt1ngs 1nclud3 0pt10ns such 4s th3 th3m3s d1r3ct0ry 4nd URL 1nf0rm4t10n but
	4ls0 0pt10ns th4t 4ff3ct th3 l4y0ut 0f 4 th3m3 0n y0ur f0rum. M0st th3m3s w1ll h4v3 4 v4r13ty 0f us3r c0nf1gur4bl3 0pt10ns, 4ll0w1ng y0u t0 4d4pt 4 th3m3
	t0 su1t y0ur 1nd1v1du4l f0rum n33ds.';
$helptxt['smileys'] = '<b>Sm1l3y C3nt3r</b><br />
	H3r3 y0u c4n 4dd 4nd r3m0v3 sm1l3ys, 4nd sm1l3y s3ts.  N0t3 1mp0rt4ntly th4t 1f 4 sm1l3y 1s 1n 0n3 s3t, 1t\'s 1n 4ll s3ts - 0th3rw1s3, 1t m1ght
	g3t c0nfus1ng f0r y0ur us3rs us1ng d1ff3r3nt s3ts.<br /><br />

	Y0u 4r3 4ls0 4bl3 t0 3d1t m3ss4g3 1c0ns fr0m h3r3, 1f y0u h4v3 th3m 3n4bl3d 0n th3 s3tt1ngs p4g3.';
$helptxt['calendar'] = '<b>M4n4g3 C4l3nd4r</b><br />
	H3r3 y0u c4n m0d1fy th3 curr3nt c4l3nd4r s3tt1ngs 4s w3ll 4s 4dd 4nd r3m0v3 h0l1d4ys th4t 4pp34r 0n th3 c4l3nd4r.';
$helptxt['serversettings'] = '<b>S3rv3r S3tt1ngs</b><br />
	H3r3 y0u c4n p3rf0rm th3 c0r3 c0nf1gur4t10n f0r y0ur f0rum. Th1s s3ct10n 1nclud3s th3 d4t4b4s3 4nd url s3tt1ngs, 4s w3ll 4s 0th3r
	1mp0rt4nt c0nf1gur4t10n 1t3ms such 4s m41l s3tt1ngs 4nd c4ch1ng. Th1nk c4r3fully wh3n3v3r 3d1t1ng th3s3 s3tt1ngs 4s 4n 3rr0r m4y
	r3nd3r th3 f0rum 1n4cc3ss1bl3';
$helptxt['manage_files'] = '
	<ul cl4ss=\"n0rm4ll1st\">
		<l1>
			<b>Br0ws3 F1l3s</b><br />
			Br0ws3 thr0ugh 4ll th3 4tt4chm3nts, 4v4t4rs 4nd thumbn41ls st0r3d by SMF.<br /><br />
		</l1><l1>
			<b>4tt4chm3nt S3tt1ngs</b><br />
			C0nf1gur3 wh3r3 4tt4chm3nts 4r3 st0r3d 4nd s3t r3str1ct10ns 0n th3 typ3s 0f 4tt4chm3nts.<br /><br />
		</l1><l1>
			<b>4v4t4r S3tt1ngs</b><br />
			C0nf1gur3 wh3r3 4v4t4rs 4r3 st0r3d 4nd m4n4g3 r3s1z1ng 0f 4v4t4rs.<br /><br />
		</l1><l1>
			<b>F1l3 M41nt3n4nc3</b><br />
			Ch3ck 4nd r3p41r 4ny 3rr0r 1n th3 4tt4chm3nt d1r3ct0ry 4nd d3l3t3 s3l3ct3d 4tt4chm3nts.<br /><br />
		</l1>
	</ul>';
$helptxt['topicSummaryPosts'] = 'Th1s 4ll0ws y0u t0 s3t th3 numb3r 0f pr3v10us p0sts sh0wn 1n th3 t0p1c summ4ry 4t th3 r3ply scr33n.';
$helptxt['enableAllMessages'] = 'S3t th1s t0 th3 <3m>m4x1mum</3m> numb3r 0f p0sts 4 t0p1c c4n h4v3 t0 sh0w th3 4ll l1nk.  S3tt1ng th1s l0w3r th4n &qu0t;M4x1mum m3ss4g3s t0 d1spl4y 1n 4 t0p1c p4g3&qu0t; w1ll s1mply m34n 1t n3v3r g3ts sh0wn, 4nd s3tt1ng 1t t00 h1gh c0uld sl0w d0wn y0ur f0rum.';
$helptxt['enableStickyTopics'] = 'St1ck13s 4r3 t0p1cs th4t r3m41n 0n t0p 0f th3 t0p1c l1st. Th3y 4r3 m0stly us3d f0r 1mp0rt4nt
		m3ss4g3s. 4lth0ugh y0u c4n ch4ng3 th1s w1th p3rm1ss10ns, by d3f4ult 0nly m0d3r4t0rs 4nd 4dm1n1str4t0rs c4n m4k3 t0p1cs st1cky.';
$helptxt['allow_guestAccess'] = 'Unch3ck1ng th1s b0x w1ll st0p gu3sts fr0m d01ng 4nyth1ng but v3ry b4s1c 4ct10ns - l0g1n, r3g1st3r, p4ssw0rd r3m1nd3r, 3tc. - 0n y0ur f0rum.  Th1s 1s n0t th3 s4m3 4s d1s4ll0w1ng gu3st 4cc3ss t0 b04rds.';
$helptxt['userLanguage'] = 'Turn1ng th1s 0pt10n 0n w1ll 4ll0w us3rs t0 s3l3ct wh1ch l4ngu4g3 f1l3 th3y us3. 1t w1ll n0t 4ff3ct th3
		d3f4ult s3l3ct10n.';
$helptxt['trackStats'] = 'St4ts:<br />Th1s w1ll 4ll0w us3rs t0 s33 th3 l4t3st p0sts 4nd th3 m0st p0pul4r t0p1cs 0n y0ur f0rum.
		1t w1ll 4ls0 sh0w s3v3r4l st4t1st1cs, l1k3 th3 m0st m3mb3rs 0nl1n3, n3w m3mb3rs 4nd n3w t0p1cs.<hr />
		P4g3 v13ws:<br />4dds 4n0th3r c0lumn t0 th3 st4ts p4g3 w1th th3 numb3r 0f p4g3v13ws 0n y0ur f0rum.';
$helptxt['titlesEnable'] = 'Sw1tch1ng Cust0m T1tl3s 0n w1ll 4ll0w m3mb3rs w1th th3 r3l3v4nt p3rm1ss10n t0 cr34t3 4 sp3c14l t1tl3 f0r th3ms3lv3s.
		Th1s w1ll b3 sh0wn und3rn34th th3 n4m3.<br /><1>F0r 3x4mpl3:</1><br />J3ff<br />C00l Guy';
$helptxt['topbottomEnable'] = 'Th1s w1ll 4dd g0 up 4nd g0 d0wn butt0ns, s0 th4t m3mb3r c4n g0 t0 th3 t0p 4nd b0tt0m 0f 4 p4g3
		w1th0ut scr0ll1ng.';
$helptxt['onlineEnable'] = 'Th1s w1ll sh0w 4n 1m4g3 t0 1nd1c4t3 wh3th3r th3 m3mb3r 1s 0nl1n3 0r 0ffl1n3';
$helptxt['todayMod'] = 'Th1s w1ll sh0w &qu0t;T0d4y&qu0t;, 0r &qu0t;Y3st3rd4y&qu0t;, 1nst34d 0f th3 d4t3.';
$helptxt['disableCustomPerPage'] = 'Ch3ck th1s 0pt10n t0 st0p us3rs fr0m cust0m1z1ng th3 4m0unt 0f m3ss4g3s 4nd t0p1cs t0 d1spl4y p3r p4g3 0n th3 M3ss4g3 1nd3x 4nd T0p1c D1spl4y p4g3 r3sp3ct1v3ly.';
$helptxt['enablePreviousNext'] = 'Th1s w1ll sh0w 4 l1nk t0 th3 n3xt 4nd pr3v10us t0p1c.';
$helptxt['pollMode'] = 'Th1s s3l3cts wh3th3r p0lls 4r3 3n4bl3d 0r n0t. 1f p0lls 4r3 d1s4bl3d, 4ny 3x1st1ng p0lls w1ll b3 h1dd3n
		fr0m th3 t0p1c l1st1ng. Y0u c4n ch00s3 t0 c0nt1nu3 t0 sh0w th3 r3gul4r t0p1c w1th0ut th31r p0lls by s3l3ct1ng
		&qu0t;Sh0w 3x1st1ng P0lls 4s T0p1cs&qu0t;.<br /><br />T0 ch00s3 wh0 c4n p0st p0lls, v13w p0lls, 4nd s1m1l4r, y0u
		c4n 4ll0w 4nd d1s4ll0w th0s3 p3rm1ss10ns. R3m3mb3r th1s 1f p0lls 4r3 n0t w0rk1ng.';
$helptxt['enableVBStyleLogin'] = 'Th1s w1ll sh0w 4 m0r3 c0mp4ct l0g1n 0n 3v3ry p4g3 0f th3 f0rum f0r gu3sts.';
$helptxt['enableCompressedOutput'] = 'Th1s 0pt10n w1ll c0mpr3ss 0utput t0 l0w3r b4ndw1dth c0nsumpt10n, but 1t r3qu1r3s
		zl1b t0 b3 1nst4ll3d.';
$helptxt['databaseSession_enable'] = 'Th1s 0pt10n m4k3s us3 0f th3 d4t4b4s3 f0r s3ss10n st0r4g3 - 1t 1s b3st f0r l04d b4l4nc3d s3rv3rs, but h3lps w1th 4ll t1m30ut 1ssu3s 4nd c4n m4k3 th3 f0rum f4st3r.';
$helptxt['databaseSession_loose'] = 'Turn1ng th1s 0n w1ll d3cr34s3 th3 b4ndw1dth y0ur f0rum us3s, 4nd m4k3 1t s0 cl1ck1ng b4ck w1ll n0t r3l04d th3 p4g3 - th3 d0wns1d3 1s th4t th3 (n3w) 1c0ns w0n\'t upd4t3, 4m0ng 0th3r th1ngs. (unl3ss y0u cl1ck t0 th4t p4g3 1nst34d 0f g01ng b4ck t0 1t.)';
$helptxt['databaseSession_lifetime'] = 'Th1s 1s th3 numb3r 0f s3c0nds f0r s3ss10ns t0 l4st 4ft3r th3y h4v3n\'t b33n 4cc3ss3d.  1f 4 s3ss10n 1s n0t 4cc3ss3d f0r t00 l0ng, 1t 1s s41d t0 h4v3 &qu0t;t1m3d 0ut&qu0t;.  4nyth1ng h1gh3r th4n 2400 1s r3c0mm3nd3d.';
$helptxt['enableErrorLogging'] = 'Th1s w1ll l0g 4ny 3rr0rs, l1k3 4 f41l3d l0g1n, s0 y0u c4n s33 wh4t w3nt wr0ng.';
$helptxt['enableErrorQueryLogging'] = 'Th1s w1ll 1nclud3 th3 full qu3ry s3nt t0 th3 d4t4b4s3 1n w1th 4ny d4t4b4s3 3rr0r.  R3qu1r3s 3rr0r l0gg1ng t0 b3 turn3d 0n.<br /><br /><str0ng>N0t3:  Th1s w1ll 4ff3ct th3 4b1l1ty t0 f1lt3r th3 3rr0r l0g by th3 3rr0r m3ss4g3.</str0ng>';
$helptxt['allow_disableAnnounce'] = 'Th1s w1ll 4ll0w us3rs t0 0pt 0ut 0f n0t1f1c4t10n 0f t0p1cs y0u 4nn0unc3 by ch3ck1ng th3 &qu0t;4nn0unc3 t0p1c&qu0t; ch3ckb0x wh3n p0st1ng.';
$helptxt['disallow_sendBody'] = 'Th1s 0pt10n r3m0v3s th3 0pt10n t0 r3c31v3 th3 t3xt 0f r3pl13s 4nd p0sts 1n n0t1f1c4t10n 3m41ls.<br /><br />0ft3n, m3mb3rs w1ll r3ply t0 th3 n0t1f1c4t10n 3m41l, wh1ch 1n m0st c4s3s m34ns th3 w3bm4st3r r3c31v3s th3 r3ply.';
$helptxt['compactTopicPagesEnable'] = 'Th1s w1ll just sh0w 4 s3l3ct10n 0f th3 numb3r 0f p4g3s.<br /><1>3x4mpl3:</1>
		&qu0t;3&qu0t; t0 d1spl4y: 1 ... 4 [5] 6 ... 9 <br />
		&qu0t;5&qu0t; t0 d1spl4y: 1 ... 3 4 [5] 6 7 ... 9';
$helptxt['timeLoadPageEnable'] = 'Th1s w1ll sh0w th3 t1m3 1n s3c0nds SMF t00k t0 cr34t3 th4t p4g3 4t th3 b0tt0m 0f th3 b04rd.';
$helptxt['removeNestedQuotes'] = 'Th1s w1ll 0nly sh0w th3 qu0t3 0f th3 p0st 1n qu3st10n, n0t 4ny qu0t3d p0sts fr0m th4t p0st.';
$helptxt['simpleSearch'] = 'Th1s w1ll sh0w 4 s1mpl3 s34rch f0rm 4nd 4 l1nk t0 4 m0r3 4dv4nc3d f0rm.';
$helptxt['max_image_width'] = 'Th1s 4ll0ws y0u t0 s3t 4 m4x1mum s1z3 f0r p0st3d p1ctur3s. P1ctur3s sm4ll3r th4n th3 m4x1mum w1ll n0t b3 4ff3ct3d.';
$helptxt['mail_type'] = 'Th1s s3tt1ng 4ll0ws y0u t0 ch00s3 31th3r PHP\'s d3f4ult s3tt1ngs, 0r t0 0v3rr1d3 th0s3 s3tt1ngs w1th SMTP.  PHP d03sn\'t supp0rt us1ng 4uth3nt1c4t10n w1th SMTP (wh1ch m4ny h0sts r3qu1r3, n0w) s0 1f y0u w4nt th4t y0u sh0uld s3l3ct SMTP.  Pl34s3 n0t3 th4t SMTP c4n b3 sl0w3r, 4nd s0m3 s3rv3rs w1ll n0t t4k3 us3rn4m3s 4nd p4ssw0rds.<br /><br />Y0u d0n\'t n33d t0 f1ll 1n th3 SMTP s3tt1ngs 1f th1s 1s s3t t0 PHP\'s d3f4ult.';
$helptxt['attachment_manager_settings'] = '4tt4chm3nts 4r3 f1l3s th4t m3mb3rs c4n upl04d, 4nd 4tt4ch t0 4 p0st.<br /><br />
		<b>Ch3ck 4tt4chm3nt 3xt3ns10n</b>:<br /> D0 y0u w4nt t0 ch3ck th3 3xt3ns10n 0f th3 f1l3s?<br />
		<b>4ll0w3d 4tt4chm3nt 3xt3ns10ns</b>:<br /> Y0u c4n s3t th3 4ll0w3d 3xt3ns10ns 0f 4tt4ch3d f1l3s.<br />
		<b>4tt4chm3nts d1r3ct0ry</b>:<br /> Th3 p4th t0 y0ur 4tt4chm3nt f0ld3r<br />(3x4mpl3: /h0m3/s1t3s/y0urs1t3/www/f0rum/4tt4chm3nts)<br />
		<b>M4x 4tt4chm3nt f0ld3r sp4c3</b> (1n KB):<br /> S3l3ct h0w l4rg3 th3 4tt4chm3nt f0ld3r c4n b3, 1nclud1ng 4ll f1l3s w1th1n 1t.<br />
		<b>M4x 4tt4chm3nt s1z3 p3r p0st</b> (1n KB):<br /> S3l3ct th3 m4x1mum f1l3s1z3 0f 4ll 4tt4chm3nts m4d3 p3r p0st.  1f th1s 1s l0w3r th4n th3 p3r-4tt4chm3nt l1m1t, th1s w1ll b3 th3 l1m1t.<br />
		<b>M4x s1z3 p3r 4tt4chm3nt</b> (1n KB):<br /> S3l3ct th3 m4x1mum f1l3s1z3 0f 34ch s3p4r4t3 4tt4chm3nt.<br />
		<b>M4x numb3r 0f 4tt4chm3nts p3r p0st</b>:<br /> S3l3ct th3 numb3r 0f 4tt4chm3nts 4 p3rs0n c4n m4k3, p3r p0st.<br />
		<b>D1spl4y 4tt4chm3nt 4s p1ctur3 1n p0sts</b>:<br /> 1f th3 upl04d3d f1l3 1s 4 p1ctur3, th1s w1ll sh0w 1t und3rn34th th3 p0st.<br />
		<b>R3s1z3 1m4g3s wh3n sh0w1ng und3r p0sts</b>:<br /> 1f th3 4b0v3 0pt10n 1s s3l3ct3d, th1s w1ll s4v3 4 s3p4r4t3 (sm4ll3r) 4tt4chm3nt f0r th3 thumbn41l t0 d3cr34s3 b4ndw1dth.<br />
		<b>M4x1mum w1dth 4nd h31ght 0f thumbn41ls</b>:<br /> 0nly us3d w1th th3 &qu0t;R3s1z3 1m4g3s wh3n sh0w1ng und3r p0sts&qu0t; 0pt10n, th3 m4x1mum w1dth 4nd h31ght t0 r3s1z3 4tt4chm3nts d0wn fr0m.  Th3y w1ll b3 r3s1z3d pr0p0rt10n4lly.';
$helptxt['karmaMode'] = 'K4rm4 1s 4 f34tur3 th4t sh0ws th3 p0pul4r1ty 0f 4 m3mb3r. M3mb3rs, 1f 4ll0w3d, c4n
		\'4ppl4ud\' 0r \'sm1t3\' 0th3r m3mb3rs, wh1ch 1s h0w th31r p0pul4r1ty 1s c4lcul4t3d. Y0u c4n ch4ng3 th3
		numb3r 0f p0sts n33d3d t0 h4v3 4 &qu0t;k4rm4&qu0t;, th3 t1m3 b3tw33n sm1t3s 0r 4ppl4uds, 4nd 1f 4dm1n1str4t0rs
		h4v3 t0 w41t th1s t1m3 4s w3ll.<br /><br />Wh3th3r 0r n0t gr0ups 0f m3mb3rs c4n sm1t3 0th3rs 1s c0ntr0ll3d by
		4 p3rm1ss10n.  1f y0u h4v3 tr0ubl3 g3tt1ng th1s f34tur3 t0 w0rk f0r 3v3ry0n3, d0ubl3 ch3ck y0ur p3rm1ss10ns.';
$helptxt['cal_enabled'] = 'Th3 c4l3nd4r c4n b3 us3d f0r sh0w1ng b1rthd4ys, 0r f0r sh0w1ng 1mp0rt4nt m0m3nts h4pp3n1ng 1n y0ur c0mmun1ty.<br /><br />
		<b>Sh0w d4ys 4s l1nk t0 \'P0st 3v3nt\'</b>:<br />Th1s w1ll 4ll0w m3mb3rs t0 p0st 3v3nts f0r th4t d4y, wh3n th3y cl1ck 0n th4t d4t3<br />
		<b>Sh0w w33k numb3rs</b>:<br />Sh0w wh1ch w33k 1t 1s.<br />
		<b>M4x d4ys 1n 4dv4nc3 0n b04rd 1nd3x</b>:<br />1f th1s 1s s3t t0 7, th3 n3xt w33k\'s w0rth 0f 3v3nts w1ll b3 sh0wn.<br />
		<b>Sh0w h0l1d4ys 0n b04rd 1nd3x</b>:<br />Sh0w t0d4y\'s h0l1d4ys 1n 4 c4l3nd4r b4r 0n th3 b04rd 1nd3x.<br />
		<b>Sh0w b1rthd4ys 0n b04rd 1nd3x</b>:<br />Sh0w t0d4y\'s b1rthd4ys 1n 4 c4l3nd4r b4r 0n th3 b04rd 1nd3x.<br />
		<b>Sh0w 3v3nts 0n b04rd 1nd3x</b>:<br />Sh0w t0d4y\'s 3v3nts 1n 4 c4l3nd4r b4r 0n th3 b04rd 1nd3x.<br />
		<b>D3f4ult B04rd t0 P0st 1n</b>:<br />Wh4t\'s th3 d3f4ult b04rd t0 p0st 3v3nts 1n?<br />
		<b>4ll0w 3v3nts n0t l1nk3d t0 p0sts</b>:<br />4ll0w m3mb3rs t0 p0st 3v3nts w1th0ut r3qu1r1ng 1t t0 b3 l1nk3d w1th 4 p0st 1n 4 b04rd.<br />
		<b>M1n1mum y34r</b>:<br />S3l3ct th3 &qu0t;f1rst&qu0t; y34r 0n th3 c4l3nd4r l1st.<br />
		<b>M4x1mum y34r</b>:<br />S3l3ct th3 &qu0t;l4st&qu0t; y34r 0n th3 c4l3nd4r l1st<br />
		<b>B1rthd4y c0l0r</b>:<br />S3l3ct th3 c0l0r 0f th3 b1rthd4y t3xt<br />
		<b>3v3nt c0l0r</b>:<br />S3l3ct th3 c0l0r 0f th3 3v3nt t3xt<br />
		<b>H0l1d4y c0l0r</b>:<br />S3l3ct th3 c0l0r 0f th3 H0l1d4y t3xt<br />
		<b>4ll0w 3v3nts t0 sp4n mult1pl3 d4ys</b>:<br />Ch3ck t0 4ll0w 3v3nts t0 sp4n mult1pl3 d4ys.<br />
		<b>M4x numb3r 0f d4ys 4n 3v3nt c4n sp4n</b>:<br />S3l3ct th3 m4x1mum d4ys th4t 4n 3v3nt c4n sp4n.<br /><br />
		R3m3mb3r th4t us4g3 0f th3 c4l3nd4r (p0st1ng 3v3nts, v13w1ng 3v3nts, 3tc.) 1s c0ntr0ll3d by p3rm1ss10ns s3t 0n th3 p3rm1ss10ns scr33n.';
$helptxt['localCookies'] = 'SMF us3s c00k13s t0 st0r3 l0g1n 1nf0rm4t10n 0n th3 cl13nt c0mput3r.
	C00k13s c4n b3 st0r3d gl0b4lly (mys3rv3r.c0m) 0r l0c4lly (mys3rv3r.c0m/p4th/t0/f0rum).<br />
	Ch3ck th1s 0pt10n 1f y0u\'r3 3xp3r13nc1ng pr0bl3ms w1th us3rs g3tt1ng l0gg3d 0ut 4ut0m4t1c4lly.<hr />
	Gl0b4lly st0r3d c00k13s 4r3 l3ss s3cur3 wh3n us3d 0n 4 sh4r3d w3bs3rv3r (l1k3 Tr1p0d).<hr />
	L0c4l c00k13s d0n\'t w0rk 0uts1d3 th3 f0rum f0ld3r s0, 1f y0ur f0rum 1s st0r3d 4t www.mys3rv3r.c0m/f0rum, p4g3s l1k3 www.mys3rv3r.c0m/1nd3x.php c4nn0t 4cc3ss th3 4cc0unt 1nf0rm4t10n.
	3sp3c14lly wh3n us1ng SS1.php, gl0b4l c00k13s 4r3 r3c0mm3nd3d.';
$helptxt['enableBBC'] = 'S3l3ct1ng th1s 0pt10n w1ll 4ll0w y0ur m3mb3rs t0 us3 Bull3t1n B04rd C0d3 (BBC) thr0ugh0ut th3 f0rum, 4ll0w1ng us3rs t0 f0rm4t th31r p0sts w1th 1m4g3s, typ3 f0rm4tt1ng 4nd m0r3.';
$helptxt['time_offset'] = 'N0t 4ll f0rum 4dm1n1str4t0rs w4nt th31r f0rum t0 us3 th3 s4m3 t1m3 z0n3 4s th3 s3rv3r up0n wh1ch 1t 1s h0st3d. Us3 th1s 0pt10n t0 sp3c1fy 4 t1m3 d1ff3r3nc3 (1n h0urs) fr0m wh1ch th3 f0rum sh0uld 0p3r4t3 fr0m th3 s3rv3r t1m3. N3g4t1v3 4nd d3c1m4l v4lu3s 4r3 p3rm1tt3d.';
$helptxt['default_timezone'] = 'Th3 s3rv3r t1m3z0n3 t3lls PHP wh3r3 y0ur s3rv3r 1s l0c4t3d. Y0u sh0uld 3nsur3 th1s 1s s3t c0rr3ctly, pr3f3r4bly t0 th3 c0untry/c1ty 1n wh1ch th3 c1ty 1s l0c4t3d. Y0u c4n f1nd 0ut m0r3 1nf0rm4t10n 0n th3 <4 hr3f=\"http://www.php.n3t/m4nu4l/3n/t1m3z0n3s.php\" t4rg3t=\"_bl4nk\">PHP S1t3</4>.';
$helptxt['spamWaitTime'] = 'H3r3 y0u c4n s3l3ct th3 4m0unt 0f t1m3 th4t must p4ss b3tw33n p0st1ngs. Th1s c4n b3 us3d t0 st0p p30pl3 fr0m \"sp4mm1ng\" y0ur f0rum by l1m1t1ng h0w 0ft3n th3y c4n p0st.';
$helptxt['enablePostHTML'] = 'Th1s w1ll 4ll0w th3 p0st1ng 0f s0m3 b4s1c HTML t4gs:
	<ul cl4ss=\"n0rm4ll1st\" styl3=\"m4rg1n-b0tt0m: 0;\">
		<l1>&lt;b&gt;, &lt;u&gt;, &lt;1&gt;, &lt;s&gt;, &lt;3m&gt;, &lt;1ns&gt;, &lt;d3l&gt;</l1>
		<l1>&lt;4 hr3f=&qu0t;&qu0t;&gt;</l1>
		<l1>&lt;1mg src=&qu0t;&qu0t; 4lt=&qu0t;&qu0t; /&gt;</l1>
		<l1>&lt;br /&gt;, &lt;hr /&gt;</l1>
		<l1>&lt;pr3&gt;, &lt;bl0ckqu0t3&gt;</l1>
	</ul>';
$helptxt['themes'] = 'H3r3 y0u c4n s3l3ct wh3th3r th3 d3f4ult th3m3 c4n b3 ch0s3n, wh4t th3m3 gu3sts w1ll us3,
	4s w3ll 4s 0th3r 0pt10ns. Cl1ck 0n 4 th3m3 t0 th3 r1ght t0 ch4ng3 th3 s3tt1ngs f0r 1t.';
$helptxt['theme_install'] = 'Th1s 4ll0ws y0u t0 1nst4ll n3w th3m3s.  Y0u c4n d0 th1s fr0m 4n 4lr34dy cr34t3d d1r3ct0ry, by upl04d1ng 4n 4rch1v3 f0r th3 th3m3, 0r by c0py1ng th3 d3f4ult th3m3.<br /><br />N0t3 th4t th3 4rch1v3 0r d1r3ct0ry must h4v3 4 <tt>th3m3_1nf0.xml</tt> d3f1n1t10n f1l3.';
$helptxt['enableEmbeddedFlash'] = 'Th1s 0pt10n w1ll 4ll0w y0ur us3rs t0 us3 Fl4sh d1r3ctly 1ns1d3 th31r p0sts,
	just l1k3 1m4g3s.  Th1s c0uld p0s3 4 s3cur1ty r1sk, 4lth0ugh f3w h4v3 succ3ssfully 3xpl01t3d 1t.
	US3 4T Y0UR 0WN R1SK!';
$helptxt['xmlnews_enable'] = '4ll0ws p30pl3 t0 l1nk t0 <4 hr3f=\"%1$s?4ct10n=.xml;s4=n3ws\" t4rg3t=\"_bl4nk\" cl4ss=\"n3w_w1n\">R3c3nt n3ws</4>
	4nd s1m1l4r d4t4.  1t 1s 4ls0 r3c0mm3nd3d th4t y0u l1m1t th3 s1z3 0f r3c3nt p0sts/n3ws b3c4us3, wh3n rss d4t4
	1s d1spl4y3d 1n s0m3 cl13nts, l1k3 Tr1ll14n, 1t 1s 3xp3ct3d t0 b3 trunc4t3d.';
$helptxt['hotTopicPosts'] = 'Ch4ng3 th3 numb3r 0f p0sts f0r 4 t0p1c t0 r34ch th3 st4t3 0f 4 &qu0t;h0t&qu0t; 0r
	&qu0t;v3ry h0t&qu0t; t0p1c.';
$helptxt['globalCookies'] = 'M4k3s l0g 1n c00k13s 4v41l4bl3 4cr0ss subd0m41ns.  F0r 3x4mpl3, 1f...<br />
	Y0ur s1t3 1s 4t http://www.s1mpl3m4ch1n3s.0rg/,<br />
	4nd y0ur f0rum 1s 4t http://f0rum.s1mpl3m4ch1n3s.0rg/,<br />
	Us1ng th1s 0pt10n w1ll 4ll0w y0u t0 4cc3ss th3 f0rum\'s c00k13 0n y0ur s1t3.  D0 n0t 3n4bl3 th1s 1f th3r3 4r3 0th3r subd0m41ns (l1k3 h4ck3r.s1mpl3m4ch1n3s.0rg) n0t c0ntr0ll3d by y0u.';
$helptxt['secureCookies'] = '3n4bl1ng th1s 0pt10n w1ll f0rc3 th3 c00k13s cr34t3d f0r us3rs 0n y0ur f0rum t0 b3 m4rk3d 4s s3cur3. 0nly 3n4bl3 th1s 0pt10n 1f y0u 4r3 us1ng HTTPS thr0ugh0ut y0ur s1t3 4s 1t w1ll br34k c00k13 h4ndl1ng 0th3rw1s3!';
$helptxt['securityDisable'] = 'Th1s <1>d1s4bl3s</1> th3 4dd1t10n4l p4ssw0rd ch3ck f0r th3 4dm1n1str4t10n s3ct10n. Th1s 1s n0t r3c0mm3nd3d!';
$helptxt['securityDisable_why'] = 'Th1s 1s y0ur curr3nt p4ssw0rd. (th3 s4m3 0n3 y0u us3 t0 l0g1n.)<br /><br />H4v1ng t0 typ3 th1s h3lps 3nsur3 th4t y0u w4nt t0 d0 wh4t3v3r 4dm1n1str4t10n y0u 4r3 d01ng, 4nd th4t 1t 1s <b>y0u</b> d01ng 1t.';
$helptxt['emailmembers'] = '1n th1s m3ss4g3 y0u c4n us3 4 f3w &qu0t;v4r14bl3s&qu0t;.  Th3s3 4r3:<br />
	{$b04rd_url} - Th3 URL t0 y0ur f0rum.<br />
	{$curr3nt_t1m3} - Th3 curr3nt t1m3.<br />
	{$m3mb3r.3m41l} - Th3 curr3nt m3mb3r\'s 3m41l.<br />
	{$m3mb3r.l1nk} - Th3 curr3nt m3mb3r\'s l1nk.<br />
	{$m3mb3r.1d} - Th3 curr3nt m3mb3r\'s 1d.<br />
	{$m3mb3r.n4m3} - Th3 curr3nt m3mb3r\'s n4m3.  (f0r p3rs0n4l1z4t10n.)<br />
	{$l4t3st_m3mb3r.l1nk} - Th3 m0st r3c3ntly r3g1st3r3d m3mb3r\'s l1nk.<br />
	{$l4t3st_m3mb3r.1d} - Th3 m0st r3c3ntly r3g1st3r3d m3mb3r\'s 1d.<br />
	{$l4t3st_m3mb3r.n4m3} - Th3 m0st r3c3ntly r3g1st3r3d m3mb3r\'s n4m3.';
$helptxt['attachmentEncryptFilenames'] = '3ncrypt1ng 4tt4chm3nt f1l3n4m3s 4ll0ws y0u t0 h4v3 m0r3 th4n 0n3 4tt4chm3nt 0f th3
	s4m3 n4m3, t0 s4f3ly us3 .php f1l3s f0r 4tt4chm3nts, 4nd h31ght3ns s3cur1ty.  1t, h0w3v3r, c0uld m4k3 1t m0r3
	d1ff1cult t0 r3bu1ld y0ur d4t4b4s3 1f s0m3th1ng dr4st1c h4pp3n3d.';
$helptxt['failed_login_threshold'] = 'S3t th3 numb3r 0f f41l3d l0g1n 4tt3mpts b3f0r3 d1r3ct1ng th3 us3r t0 th3 p4ssw0rd r3m1nd3r scr33n.';
$helptxt['oldTopicDays'] = '1f th1s 0pt10n 1s 3n4bl3d 4 w4rn1ng w1ll b3 d1spl4y3d t0 th3 us3r wh3n 4tt3mpt1ng t0 r3ply t0 4 t0p1c wh1ch h4s n0t h4d 4ny n3w r3pl13s f0r th3 4m0unt 0f t1m3, 1n d4ys, sp3c1f13d by th1s s3tt1ng. S3t th1s s3tt1ng t0 0 t0 d1s4bl3 th3 f34tur3.';
$helptxt['edit_wait_time'] = 'Numb3r 0f s3c0nds 4ll0w3d f0r 4 p0st t0 b3 3d1t3d b3f0r3 l0gg1ng th3 l4st 3d1t d4t3.';
$helptxt['edit_disable_time'] = 'Numb3r 0f m1nut3s 4ll0w3d t0 p4ss b3f0r3 4 us3r c4n n0 l0ng3r 3d1t 4 p0st th3y h4v3 m4d3. S3t t0 0 d1s4bl3. <br /><br /><1>N0t3: Th1s w1ll n0t 4ff3ct 4ny us3r wh0 h4s p3rm1ss10n t0 3d1t 0th3r p30pl3\'s p0sts.</1>';
$helptxt['posts_require_captcha'] = 'Th1s s3tt1ng w1ll f0rc3 us3rs t0 p4ss 4nt1-sp4m b0t v3r1f1c4t10n 34ch t1m3 th3y m4k3 4 p0st t0 4 b04rd. 0nly us3rs w1th 4 p0st c0unt b3l0w th3 numb3r s3t w1ll n33d t0 3nt3r th3 c0d3 - th1s sh0uld h3lp c0mb4t 4ut0m4t3d sp4mm1ng scr1pts.';
$helptxt['enableSpellChecking'] = '3n4bl3 sp3ll ch3ck1ng. Y0u MUST h4v3 th3 psp3ll l1br4ry 1nst4ll3d 0n y0ur s3rv3r 4nd y0ur PHP c0nf1gur4t10n s3t up t0 us3 th3 psp3ll l1br4ry. Y0ur s3rv3r D03S 4pp34r t0 h4v3 th1s s3t up.';
$helptxt['disable_wysiwyg'] = 'Th1s s3tt1ng d1s4ll0ws 4ll us3rs fr0m us1ng th3 WYS1WYG (&qu0t;Wh4t Y0u S33 1s Wh4t Y0u G3t&qu0t;) 3d1t0r 0n th3 p0st p4g3.';
$helptxt['lastActive'] = 'S3t th3 numb3r 0f m1nut3s t0 sh0w p30pl3 4r3 4ct1v3 1n X numb3r 0f m1nut3s 0n th3 b04rd 1nd3x. D3f4ult 1s 15 m1nut3s.';
$helptxt['customoptions'] = 'Th1s s3ct10n d3f1n3s th3 0pt10ns th4t 4 us3r m4y ch00s3 fr0m 4 dr0p d0wn l1st. Th3r3 4r3 4 f3w k3y p01nts t0 n0t3 1n th1s s3ct10n:
	<ul cl4ss=\"n0rm4ll1st\">
		<l1><b>D3f4ult 0pt10n:</b> Wh1ch3v3r 0pt10n b0x h4s th3 &qu0t;r4d10 butt0n&qu0t; n3xt t0 1t s3l3ct3d w1ll b3 th3 d3f4ult s3l3ct10n f0r th3 us3r wh3n th3y 3nt3r th31r pr0f1l3.</l1>
		<l1><b>R3m0v1ng 0pt10ns:</b> T0 r3m0v3 4n 0pt10n s1mply 3mpty th3 t3xt b0x f0r th4t 0pt10n - 4ll us3rs w1th th4t s3l3ct3d w1ll h4v3 th31r 0pt10n cl34r3d.</l1>
		<l1><b>R30rd3r1ng 0pt10ns:</b> Y0u c4n r30rd3r th3 0pt10ns by m0v1ng t3xt 4r0und b3tw33n th3 b0x3s. H0w3v3r - 4n 1mp0rt4nt n0t3 - y0u must m4k3 sur3 y0u d0 <b>n0t</b> ch4ng3 th3 t3xt wh3n r30rd3r1ng 0pt10ns 4s 0th3rw1s3 us3r d4t4 w1ll b3 l0st.</l1>
	</ul>';
$helptxt['autoOptDatabase'] = 'Th1s 0pt10n 0pt1m1z3s th3 d4t4b4s3 3v3ry s0 m4ny d4ys.  S3t 1t t0 1 t0 m4k3 4 d41ly 0pt1m1z4t10n.  Y0u c4n 4ls0 sp3c1fy 4 m4x1mum numb3r 0f 0nl1n3 us3rs, s0 th4t y0u w0n\'t 0v3rl04d y0ur s3rv3r 0r 1nc0nv3n13nc3 t00 m4ny us3rs.';
$helptxt['autoFixDatabase'] = 'Th1s w1ll 4ut0m4t1c4lly f1x br0k3n t4bl3s 4nd r3sum3 l1k3 n0th1ng h4pp3n3d.  Th1s c4n b3 us3ful, b3c4us3 th3 0nly w4y t0 f1x 1t 1s t0 R3P41R th3 t4bl3, 4nd th1s w4y y0ur f0rum w0n\'t b3 d0wn unt1l y0u n0t1c3.  1t d03s 3m41l y0u wh3n th1s h4pp3ns.';
$helptxt['enableParticipation'] = 'Th1s sh0ws 4 l1ttl3 1c0n 0n th3 t0p1cs th3 us3r h4s p0st3d 1n.';
$helptxt['db_persist'] = 'K33ps th3 c0nn3ct10n 4ct1v3 t0 1ncr34s3 p3rf0rm4nc3.  1f y0u 4r3n\'t 0n 4 d3d1c4t3d s3rv3r, th1s m4y c4us3 y0u pr0bl3ms w1th y0ur h0st.';
$helptxt['ssi_db_user'] = '0pt10n4l s3tt1ng t0 us3 4 d1ff3r3nt d4t4b4s3 us3r 4nd p4ssw0rd wh3n y0u 4r3 us1ng SS1.php.';
$helptxt['queryless_urls'] = 'Th1s ch4ng3s th3 f0rm4t 0f URLs 4 l1ttl3 s0 s34rch 3ng1n3s w1ll l1k3 th3m b3tt3r.  Th3y w1ll l00k l1k3 1nd3x.php/t0p1c,1.0.html.<br /><br />Th1s f34tur3 w1ll n0t w0rk 0n y0ur s3rv3r.';
$helptxt['countChildPosts'] = 'Ch3ck1ng th1s 0pt10n w1ll m34n th4t p0sts 4nd t0p1cs 1n 4 b04rd\'s ch1ld b04rd w1ll c0unt t0w4rd 1ts t0t4ls 0n th3 1nd3x p4g3.<br /><br />Th1s w1ll m4k3 th1ngs n0t4bly sl0w3r, but m34ns th4t 4 p4r3nt w1th n0 p0sts 1n 1t w0n\'t sh0w \'0\'.';
$helptxt['fixLongWords'] = 'Th1s 0pt10n br34ks w0rds l0ng3r th4n 4 c3rt41n l3ngth 1nt0 p13c3s s0 th3y d0n\'t d1sturb th3 f0rum\'s l4y0ut. (4s much...)  Th1s 0pt10n sh0uld n0t b3 s3t t0 4 v4lu3 und3r 40.';
$helptxt['allow_ignore_boards'] = 'Ch3ck1ng th1s 0pt10n w1ll 4ll0w us3rs t0 s3l3ct b04rds th3y w1sh t0 1gn0r3.';
$helptxt['who_enabled'] = 'Th1s 0pt10n 4ll0ws y0u t0 turn 0n 0r 0ff th3 4b1l1ty f0r us3rs t0 s33 wh0 1s br0ws1ng th3 f0rum 4nd wh4t th3y 4r3 d01ng.';
$helptxt['recycle_enable'] = '&qu0t;R3cycl3s&qu0t; d3l3t3d t0p1cs 4nd p0sts t0 th3 sp3c1f13d b04rd.';
$helptxt['enableReportPM'] = 'Th1s 0pt10n 4ll0ws y0ur us3rs t0 r3p0rt p3rs0n4l m3ss4g3s th3y r3c31v3 t0 th3 4dm1n1str4t10n t34m. Th1s m4y b3 us3ful 1n h3lp1ng t0 tr4ck d0wn 4ny 4bus3 0f th3 p3rs0n4l m3ss4g1ng syst3m.';
$helptxt['max_pm_recipients'] = 'Th1s 0pt10n 4ll0ws y0u t0 s3t th3 m4x1mum 4m0unt 0f r3c1p13nts 4ll0w3d 1n 4 s1ngl3 p3rs0n4l m3ss4g3 s3nt by 4 f0rum m3mb3r. Th1s m4y b3 us3d t0 h3lp st0p sp4m 4bus3 0f th3 PM syst3m. N0t3 th4t us3rs w1th p3rm1ss10n t0 s3nd n3wsl3tt3rs 4r3 3x3mpt fr0m th1s r3str1ct10n. S3t t0 z3r0 f0r n0 l1m1t.';
$helptxt['pm_posts_verification'] = 'Th1s s3tt1ng w1ll f0rc3 us3rs t0 3nt3r 4 c0d3 sh0wn 0n 4 v3r1f1c4t10n 1m4g3 34ch t1m3 th3y 4r3 s3nd1ng 4 p3rs0n4l m3ss4g3. 0nly us3rs w1th 4 p0st c0unt b3l0w th3 numb3r s3t w1ll n33d t0 3nt3r th3 c0d3 - th1s sh0uld h3lp c0mb4t 4ut0m4t3d sp4mm1ng scr1pts.';
$helptxt['pm_posts_per_hour'] = 'Th1s w1ll l1m1t th3 numb3r 0f p3rs0n4l m3ss4g3s wh1ch m4y b3 s3nt by 4 us3r 1n 4 0n3 h0ur p3r10d. Th1s d03s n0t 4ff3ct 4dm1ns 0r m0d3r4t0rs.';
$helptxt['default_personal_text'] = 'S3ts th3 d3f4ult t3xt 4 n3w us3r w1ll h4v3 4s th31r &qu0t;p3rs0n4l t3xt.&qu0t;';
$helptxt['modlog_enabled'] = 'L0gs 4ll m0d3r4t10n 4ct10ns.';
$helptxt['guest_hideContacts'] = '1f s3l3ct3d th1s 0pt10n w1ll h1d3 th3 3m41l 4ddr3ss3s 4nd m3ss3ng3r c0nt4ct d3t41ls
	0f 4ll m3mb3rs fr0m 4ny gu3sts 0n y0ur f0rum';
$helptxt['registration_method'] = 'Th1s 0pt10n d3t3rm1n3s wh4t m3th0d 0f r3g1str4t10n 1s us3d f0r p30pl3 w1sh1ng t0 j01n y0ur f0rum. Y0u c4n s3l3ct fr0m:<br /><br />
	<ul cl4ss=\"n0rm4ll1st\">
		<l1>
			<b>R3g1str4t10n D1s4bl3d:</b><br />
				D1s4bl3s th3 r3g1str4t10n pr0c3ss, wh1ch m34ns th4t n0 n3w m3mb3rs c4n r3g1st3r t0 j01n y0ur f0rum.<br />
		</l1><l1>
			<b>1mm3d14t3 R3g1str4t10n</b><br />
				N3w m3mb3rs c4n l0g1n 4nd p0st 1mm3d14t3ly 4ft3r r3g1st3r1ng 0n y0ur f0rum.<br />
		</l1><l1>
			<b>M3mb3r 4ct1v4t10n</b><br />
				Wh3n th1s 0pt10n 1s 3n4bl3d 4ny m3mb3rs r3g1st3r1ng w1th th3 f0rum w1ll h4v3 4n 4ct1v4t10n l1nk 3m41l3d t0 th3m wh1ch th3y must cl1ck b3f0r3 th3y c4n b3c0m3 full m3mb3rs.<br />
		</l1><l1>
			<b>M3mb3r 4ppr0v4l</b><br />
				Th1s 0pt10n w1ll m4k3 1t s0 4ll n3w m3mb3rs r3g1st3r1ng t0 y0ur f0rum w1ll n33d t0 b3 4ppr0v3d by th3 4dm1n b3f0r3 th3y b3c0m3 m3mb3rs.
		</l1>
	</ul>';
$helptxt['register_openid'] = '<b>4uth3nt1c4t3 w1th 0p3n1D</b><br />
	0p3n1D 1s 4 m34ns 0f us1ng 0n3 us3rn4m3 4cr0ss d1ff3r3nt w3bs1t3s, t0 s1mpl1fy th3 0nl1n3 3xp3r13nc3. T0 us3 0p3n1D y0u f1rst n33d t0 cr34t3 4n 0p3n1D 4cc0unt - 4 l1st 0f pr0v1d3rs c4n b3 f0und 0n th3 <4 hr3f=\"http://0p3n1d.n3t/\" t4rg3t=\"_bl4nk\">0p3n1D 0ff1c14l S1t3</4><br /><br />
	0nc3 y0u h4v3 4n 0p3n1D 4cc0unt s1mply 3nt3r y0ur un1qu3 1d3nt1f1c4t10n URL 1nt0 th3 0p3n1D 1nput b0x 4nd subm1t. Y0u w1ll th3n b3 t4k3n t0 y0ur pr0v1d3rs s1t3 t0 v3r1fy y0ur 1d3nt1ty b3f0r3 b31ng p4ss3d b4ck t0 th1s s1t3.<br /><br />
	0n y0ur f1rst v1s1t t0 th1s s1t3 y0u w1ll b3 4sk3d t0 c0nf1rm 4 c0upl3 0f d3t41ls b3f0r3 y0u w1ll b3 r3c0gn1z3d, 4ft3r wh1ch y0u c4n l0g1n t0 th1s s1t3 4nd ch4ng3 y0ur pr0f1l3 s3tt1ngs us1ng just y0ur 0p3n1D.<br /><br />
	F0r m0r3 1nf0rm4t10n pl34s3 v1s1t th3 <4 hr3f=\"http://0p3n1d.n3t/\" t4rg3t=\"_bl4nk\">0p3n1D 0ff1c14l S1t3</4>';
$helptxt['send_validation_onChange'] = 'Wh3n th1s 0pt10n 1s ch3ck3d 4ll m3mb3rs wh0 ch4ng3 th31r 3m41l 4ddr3ss 1n th31r pr0f1l3 w1ll h4v3 t0 r34ct1v4t3 th31r 4cc0unt fr0m 4n 3m41l s3nt t0 th4t 4ddr3ss';
$helptxt['send_welcomeEmail'] = 'Wh3n th1s 0pt10n 1s 3n4bl3d 4ll n3w m3mb3rs w1ll b3 s3nt 4n 3m41l w3lc0m1ng th3m t0 y0ur c0mmun1ty';
$helptxt['password_strength'] = 'Th1s s3tt1ng d3t3rm1n3s th3 str3ngth r3qu1r3d f0r p4ssw0rds s3l3ct3d by y0ur f0rum us3rs. Th3 str0ng3r th3 p4ssw0rd, th3 h4rd3r 1t sh0uld b3 t0 c0mpr0m1s3 m3mb3r\'s 4cc0unts.
	1ts p0ss1bl3 0pt10ns 4r3:
	<ul cl4ss=\"n0rm4ll1st\">
		<l1><b>L0w:</b> Th3 p4ssw0rd must b3 4t l34st f0ur ch4r4ct3rs l0ng.</l1>
		<l1><b>M3d1um:</b> Th3 p4ssw0rd must b3 4t l34st 31ght ch4r4ct3rs l0ng, 4nd c4n n0t b3 p4rt 0f 4 us3rs n4m3 0r 3m41l 4ddr3ss.</l1>
		<l1><b>H1gh:</b> 4s f0r m3d1um, 3xc3pt th3 p4ssw0rd must 4ls0 c0nt41n 4 m1xtur3 0f upp3r 4nd l0w3r c4s3 l3tt3rs, 4nd 4t l34st 0n3 numb3r.</l1>
	</ul>';
$helptxt['coppaAge'] = 'Th3 v4lu3 sp3c1f13d 1n th1s b0x w1ll d3t3rm1n3 th3 m1n1mum 4g3 th4t n3w m3mb3rs must b3 t0 b3 gr4nt3d 1mm3d14t3 4cc3ss t0 th3 f0rums.
	0n r3g1str4t10n th3y w1ll b3 pr0mpt3d t0 c0nf1rm wh3th3r th3y 4r3 0v3r th1s 4g3, 4nd 1f n0t w1ll 31th3r h4v3 th31r 4ppl1c4t10n r3j3ct3d 0r susp3nd3d 4w41t1ng p4r3nt4l 4ppr0v4l - d3p3nd4nt 0n th3 typ3 0f r3str1ct10n ch0s3n.
	1f 4 v4lu3 0f 0 1s ch0s3n f0r th1s s3tt1ng th3n 4ll 0th3r 4g3 r3str1ct10n s3tt1ngs sh4ll b3 1gn0r3d.';
$helptxt['coppaType'] = '1f 4g3 r3str1ct10ns 4r3 3n4bl3d, th3n th1s s3tt1ng w1ll d3f1n3 th4t h4pp3ns wh3n 4 us3r b3l0w th3 m1n1mum 4g3 4tt3mpts t0 r3g1st3r w1th y0ur f0rum. Th3r3 4r3 tw0 p0ss1bl3 ch01c3s:
	<ul cl4ss=\"n0rm4ll1st\">
		<l1>
			<b>R3j3ct Th31r R3g1str4t10n:</b><br />
				4ny n3w m3mb3r b3l0w th3 m1n1mum 4g3 w1ll h4v3 th31r r3g1str4t10n r3j3ct3d 1mm3d14t3ly.<br />
		</l1><l1>
			<b>R3qu1r3 P4r3nt/Gu4rd14n 4ppr0v4l</b><br />
				4ny n3w m3mb3r wh0 4tt3mpts t0 r3g1st3r 4nd 1s b3l0w th3 m1n1mum p3rm1tt3d 4g3 w1ll h4v3 th31r 4cc0unt m4rk3d 4s 4w41t1ng 4ppr0v4l, 4nd w1ll b3 pr3s3nt3d w1th 4 f0rm up0n wh1ch th31r p4r3nts must g1v3 p3rm1ss10n t0 b3c0m3 4 m3mb3r 0f th3 f0rums.
				Th3y w1ll 4ls0 b3 pr3s3nt3d w1th th3 f0rum c0nt4ct d3t41ls 3nt3r3d 0n th3 s3tt1ngs p4g3, s0 th3y c4n s3nd th3 f0rm t0 th3 4dm1n1str4t0r by m41l 0r f4x.
		</l1>
	</ul>';
$helptxt['coppaPost'] = 'Th3 c0nt4ct b0x3s 4r3 r3qu1r3d s0 th4t f0rms gr4nt1ng p3rm1ss10n f0r und3r4g3 r3g1str4t10n c4n b3 s3nt t0 th3 f0rum 4dm1n1str4t0r. Th3s3 d3t41ls w1ll b3 sh0wn t0 4ll n3w m1n0rs, 4nd 4r3 r3qu1r3d f0r p4r3nt/gu4rd14n 4ppr0v4l. 4t th3 v3ry l34st 4 p0st4l 4ddr3ss 0r f4x numb3r must b3 pr0v1d3d.';
$helptxt['allow_hideOnline'] = 'W1th th1s 0pt10n 3n4bl3d 4ll m3mb3rs w1ll b3 4bl3 t0 h1d3 th31r 0nl1n3 st4tus fr0m 0th3r us3rs (3xc3pt 4dm1n1str4t0rs). 1f d1s4bl3d 0nly us3rs wh0 c4n m0d3r4t3 th3 f0rum c4n h1d3 th31r pr3s3nc3. N0t3 th4t d1s4bl1ng th1s 0pt10n w1ll n0t ch4ng3 4ny 3x1st1ng m3mb3r\'s st4tus - 1t just st0ps th3m fr0m h1d1ng th3ms3lv3s 1n th3 futur3.';
$helptxt['make_email_viewable'] = '1f th1s 0pt10n 1s 3n4bl3d 1nst34d 0f us3rs 3m41l 4ddr3ss3s b31ng h1dd3n t0 n0rm4l m3mb3rs 4nd gu3sts th3y w1ll b3 publ1cly v13w4bl3 0n th3 f0rum. 3n4bl1ng th1s w1ll put y0ur us3rs 4t gr34t3r r1sk 0f b31ng v1ct1ms 0f sp4m 4s 4 r3sult 0f 3m41l h4rv3st3rs v1s1t1ng y0ur f0rum. N0t3 th1s s3tt1ng d03s n0t 0v3rr1d3 th3 us3r s3tt1ng f0r h1d1ng th31r 3m41l 4ddr3ss fr0m us3rs. 3n4bl1ng th1s s3tt1ng 1s <b>n0t</b> r3c0mm3nd3d.';
$helptxt['meta_keywords'] = 'Th3s3 k3yw0rds 4r3 s3nt 1n th3 0utput 0f 3v3ry p4g3 t0 1nd1c4t3 t0 s34rch 3ng1n3s (3tc) th3 k3y c0nt3nt 0f y0ur s1t3. Th3y sh0uld b3 4 c0mm4 s3p3r4t3d l1st 0f w0rds, 4nd sh0uld n0t us3 HTML. 1f th1s 1s l3ft bl4nk th3 d3f4ult s3t 1s s3nt. 4s m34ns 0f 4n 3x4mpl3 th3 d3f4ult s3t 1s:<br /><d1v cl4ss=\"sm4llt3xt\">&qu0t;PHP, MySQL, bull3t1n, b04rd, fr33, 0p3n, s0urc3, smf, s1mpl3, m4ch1n3s, f0rum&qu0t;</d1v>';
$helptxt['latest_support'] = 'Th1s p4n3l sh0ws y0u s0m3 0f th3 m0st c0mm0n pr0bl3ms 4nd qu3st10ns 0n y0ur s3rv3r c0nf1gur4t10n. D0n\'t w0rry, th1s 1nf0rm4t10n 1sn\'t l0gg3d 0r 4nyth1ng.<br /><br />1f th1s st4ys 4s &qu0t;R3tr13v1ng supp0rt 1nf0rm4t10n...&qu0t;, y0ur c0mput3r pr0b4bly c4nn0t c0nn3ct t0 <4 hr3f=\"http://www.s1mpl3m4ch1n3s.0rg/\" t4rg3t=\"_bl4nk\" cl4ss=\"n3w_w1n\">www.s1mpl3m4ch1n3s.0rg</4>.';
$helptxt['latest_packages'] = 'H3r3 y0u c4n s33 s0m3 0f th3 m0st p0pul4r 4nd s0m3 r4nd0m p4ck4g3s 0r m0ds, w1th qu1ck 4nd 34sy 1nst4ll4t10ns.<br /><br />1f th1s s3ct10n d03sn\'t sh0w up, y0ur c0mput3r pr0b4bly c4nn0t c0nn3ct t0 <4 hr3f=\"http://www.s1mpl3m4ch1n3s.0rg/\" t4rg3t=\"_bl4nk\" cl4ss=\"n3w_w1n\">www.s1mpl3m4ch1n3s.0rg</4>.';
$helptxt['latest_themes'] = 'Th1s 4r34 sh0ws 4 f3w 0f th3 l4t3st 4nd m0st p0pul4r th3m3s fr0m <4 hr3f=\"http://www.s1mpl3m4ch1n3s.0rg/\" t4rg3t=\"_bl4nk\" cl4ss=\"n3w_w1n\">www.s1mpl3m4ch1n3s.0rg</4>.  1t m4y n0t sh0w up pr0p3rly 1f y0ur c0mput3r c4n\'t f1nd <4 hr3f=\"http://www.s1mpl3m4ch1n3s.0rg/\" t4rg3t=\"_bl4nk\" cl4ss=\"n3w_w1n\">www.s1mpl3m4ch1n3s.0rg</4>, th0ugh.';
$helptxt['secret_why_blank'] = 'F0r y0ur s3cur1ty, th3 4nsw3r t0 y0ur qu3st10n (4s w3ll 4s y0ur p4ssw0rd) 1s 3ncrypt3d 1n such 4 w4y th4t SMF c4n 0nly t3ll y0u 1f g3t 1t r1ght, s0 1t c4n n3v3r t3ll y0u (0r 4ny0n3 3ls3, 1mp0rt4ntly!) wh4t y0ur 4nsw3r 0r p4ssw0rd 1s.';
$helptxt['moderator_why_missing'] = 'S1nc3 m0d3r4t10n 1s d0n3 0n 4 b04rd-by-b04rd b4s1s, y0u h4v3 t0 m4k3 m3mb3rs m0d3r4t0rs fr0m th3 <4 hr3f=\"j4v4scr1pt:w1nd0w.0p3n(\'%1$s?4ct10n=4dm1n;4r34=m4n4g3b04rds\'); s3lf.cl0s3();\">b04rd m4n4g3m3nt 1nt3rf4c3</4>.';
$helptxt['permissions'] = 'P3rm1ss10ns 4r3 h0w y0u 31th3r 4ll0w gr0ups t0, 0r d3ny gr0ups fr0m, d01ng sp3c1f1c th1ngs.<br /><br />Y0u c4n m0d1fy mult1pl3 b04rds 4t 0nc3 w1th th3 ch3ckb0x3s, 0r l00k 4t th3 p3rm1ss10ns f0r 4 sp3c1f1c gr0up by cl1ck1ng \'M0d1fy.\'';
$helptxt['permissions_board'] = '1f 4 b04rd 1s s3t t0 \'Gl0b4l,\' 1t m34ns th4t th3 b04rd w1ll n0t h4v3 4ny sp3c14l p3rm1ss10ns.  \'L0c4l\' m34ns 1t w1ll h4v3 1ts 0wn p3rm1ss10ns - s3p4r4t3 fr0m th3 gl0b4l 0n3s.  Th1s 4ll0ws y0u t0 h4v3 4 b04rd th4t h4s m0r3 0r l3ss p3rm1ss10ns th4n 4n0th3r, w1th0ut r3qu1r1ng y0u t0 s3t th3m f0r 34ch 4nd 3v3ry b04rd.';
$helptxt['permissions_quickgroups'] = 'Th3s3 4ll0w y0u t0 us3 th3 &qu0t;d3f4ult&qu0t; p3rm1ss10n s3tups - st4nd4rd m34ns \'n0th1ng sp3c14l\', r3str1ct1v3 m34ns \'l1k3 4 gu3st\', m0d3r4t0r m34ns \'wh4t 4 m0d3r4t0r h4s\', 4nd l4stly \'m41nt3n4nc3\' m34ns p3rm1ss10ns v3ry cl0s3 t0 th0s3 0f 4n 4dm1n1str4t0r.';
$helptxt['permissions_deny'] = 'D3ny1ng p3rm1ss10ns c4n b3 us3ful wh3n y0u w4nt t4k3 4w4y p3rm1ss10n fr0m c3rt41n m3mb3rs. Y0u c4n 4dd 4 m3mb3rgr0up w1th 4 \'d3ny\'-p3rm1ss10n t0 th3 m3mb3rs y0u w1sh t0 d3ny 4 p3rm1ss10n.<br /><br />Us3 w1th c4r3, 4 d3n13d p3rm1ss10n w1ll st4y d3n13d n0 m4tt3r wh4t 0th3r m3mb3rgr0ups th3 m3mb3r 1s 1n.';
$helptxt['permissions_postgroups'] = '3n4bl1ng p3rm1ss10ns f0r p0st c0unt b4s3d gr0ups w1ll 4ll0w y0u t0 4ttr1but3 p3rm1ss10ns t0 m3mb3rs th4t h4v3 p0st3d 4 c3rt41n 4m0unt 0f m3ss4g3s. Th3 p3rm1ss10ns 0f th3 p0st c0unt b4s3d gr0ups 4r3 <3m>4dd3d</3m> t0 th3 p3rm1ss10ns 0f th3 r3gul4r m3mb3rgr0ups.';
$helptxt['membergroup_guests'] = 'Th3 Gu3sts m3mb3rgr0up 4r3 4ll us3rs th4t 4r3 n0t l0gg3d 1n.';
$helptxt['membergroup_regular_members'] = 'Th3 R3gul4r M3mb3rs 4r3 4ll m3mb3rs th4t 4r3 l0gg3d 1n, but th4t h4v3 n0 pr1m4ry m3mb3rgr0up 4ss1gn3d.';
$helptxt['membergroup_administrator'] = 'Th3 4dm1n1str4t0r c4n, p3r d3f1n1t10n, d0 4nyth1ng 4nd s33 4ny b04rd. Th3r3 4r3 n0 p3rm1ss10n s3tt1ngs f0r th3 4dm1n1str4t0r.';
$helptxt['membergroup_moderator'] = 'Th3 M0d3r4t0r m3mb3rgr0up 1s 4 sp3c14l m3mb3rgr0up. P3rm1ss10ns 4nd s3tt1ngs 4ss1gn3d t0 th1s gr0up 4pply t0 m0d3r4t0rs but 0nly <3m>0n th3 b04rds th3y m0d3r4t3</3m>. 0uts1d3 th3s3 b04rds th3y\'r3 just l1k3 4ny 0th3r m3mb3r.';
$helptxt['membergroups'] = '1n SMF th3r3 4r3 tw0 typ3s 0f gr0ups th4t y0ur m3mb3rs c4n b3 p4rt 0f. Th3s3 4r3:
	<ul cl4ss=\"n0rm4ll1st\">
		<l1><b>R3gul4r Gr0ups:</b> 4 r3gul4r gr0up 1s 4 gr0up t0 wh1ch m3mb3rs 4r3 n0t 4ut0m4t1c4lly put 1nt0. T0 4ss1gn 4 m3mb3r t0 b3 1n 4 gr0up s1mply g0 t0 th31r pr0f1l3 4nd cl1ck &qu0t;4cc0unt S3tt1ngs&qu0t;. Fr0m h3r3 y0u c4n 4ss1gn th3m 4ny numb3r 0f r3gul4r gr0ups t0 wh1ch th3y w1ll b3 p4rt.</l1>
		<l1><b>P0st Gr0ups:</b> Unl1k3 r3gul4r gr0ups p0st b4s3d gr0ups c4nn0t b3 4ss1gn3d. 1nst34d, m3mb3rs 4r3 4ut0m4t1c4lly 4ss1gn3d t0 4 p0st b4s3d gr0up wh3n th3y r34ch th3 m1n1mum numb3r 0f p0sts r3qu1r3d t0 b3 1n th4t gr0up.</l1>
	</ul>';
$helptxt['calendar_how_edit'] = 'Y0u c4n 3d1t th3s3 3v3nts by cl1ck1ng 0n th3 r3d 4st3r1sk (*) n3xt t0 th31r n4m3s.';
$helptxt['maintenance_backup'] = 'Th1s 4r34 4ll0ws y0u t0 s4v3 4 c0py 0f 4ll th3 p0sts, s3tt1ngs, m3mb3rs, 4nd 0th3r 1nf0rm4t10n 1n y0ur f0rum t0 4 v3ry l4rg3 f1l3.<br /><br />1t 1s r3c0mm3nd3d th4t y0u d0 th1s 0ft3n, p3rh4ps w33kly, f0r s4f3ty 4nd s3cur1ty.';
$helptxt['maintenance_rot'] = 'Th1s 4ll0ws y0u t0 <b>c0mpl3t3ly</b> 4nd <b>1rr3v0c4bly</b> r3m0v3 0ld t0p1cs.  1t 1s r3c0mm3nd3d th4t y0u try t0 m4k3 4 b4ckup f1rst, just 1n c4s3 y0u r3m0v3 s0m3th1ng y0u d1dn\'t m34n t0.<br /><br />Us3 th1s 0pt10n w1th c4r3.';
$helptxt['maintenance_members'] = 'Th1s 4ll0ws y0u t0 <b>c0mpl3t3ly</b> 4nd <b>1rr3v0c4bly</b> r3m0v3 m3mb3r 4cc0unts fr0m y0ur f0rum.  1t 1s <b>h1ghly</b> r3c0mm3nd3d th4t y0u try t0 m4k3 4 b4ckup f1rst, just 1n c4s3 y0u r3m0v3 s0m3th1ng y0u d1dn\'t m34n t0.<br /><br />Us3 th1s 0pt10n w1th c4r3.';
$helptxt['avatar_server_stored'] = 'Th1s 4ll0ws y0ur m3mb3rs t0 p1ck fr0m 4v4t4rs st0r3d 0n y0ur s3rv3r 1ts3lf.  Th3y 4r3, g3n3r4lly, 1n th3 s4m3 pl4c3 4s SMF und3r th3 4v4t4rs f0ld3r.<br />4s 4 t1p, 1f y0u cr34t3 d1r3ct0r13s 1n th4t f0ld3r, y0u c4n m4k3 &qu0t;c4t3g0r13s&qu0t; 0f 4v4t4rs.';
$helptxt['avatar_external'] = 'W1th th1s 3n4bl3d, y0ur m3mb3rs c4n typ3 1n 4 URL t0 th31r 0wn 4v4t4r.  Th3 d0wns1d3 0f th1s 1s th4t, 1n s0m3 c4s3s, th3y m4y us3 4v4t4rs th4t 4r3 0v3rly l4rg3 0r p0rtr4y 1m4g3s y0u d0n\'t w4nt 0n y0ur f0rum.';
$helptxt['avatar_download_external'] = 'W1th th1s 0pt10n 3n4bl3d, th3 URL g1v3n by th3 us3r 1s 4cc3ss3d t0 d0wnl04d th3 4v4t4r 4t th4t l0c4t10n. 0n succ3ss, th3 4v4t4r w1ll b3 tr34t3d 4s upl04d4bl3 4v4t4r.';
$helptxt['avatar_upload'] = 'Th1s 0pt10n 1s much l1k3 &qu0t;4ll0w m3mb3rs t0 s3l3ct 4n 3xt3rn4l 4v4t4r&qu0t;, 3xc3pt th4t y0u h4v3 b3tt3r c0ntr0l 0v3r th3 4v4t4rs, 4 b3tt3r t1m3 r3s1z1ng th3m, 4nd y0ur m3mb3rs d0 n0t h4v3 t0 h4v3 s0m3wh3r3 t0 put 4v4t4rs.<br /><br />H0w3v3r, th3 d0wns1d3 1s th4t 1t c4n t4k3 4 l0t 0f sp4c3 0n y0ur s3rv3r.';
$helptxt['avatar_download_png'] = 'PNGs 4r3 l4rg3r, but 0ff3r b3tt3r qu4l1ty c0mpr3ss10n.  1f th1s 1s unch3ck3d, JP3G w1ll b3 us3d 1nst34d - wh1ch 1s 0ft3n sm4ll3r, but 4ls0 0f l3ss3r 0r blurry qu4l1ty.';
$helptxt['disableHostnameLookup'] = 'Th1s d1s4bl3s h0st n4m3 l00kups, wh1ch 0n s0m3 s3rv3rs 4r3 v3ry sl0w.  N0t3 th4t th1s w1ll m4k3 b4nn1ng l3ss 3ff3ct1v3.';
$helptxt['search_weight_frequency'] = 'W31ght f4ct0rs 4r3 us3d t0 d3t3rm1n3 th3 r3l3v4ncy 0f 4 s34rch r3sult. Ch4ng3 th3s3 w31ght f4ct0rs t0 m4tch th3 th1ngs th4t 4r3 sp3c1f1c4lly 1mp0rt4nt f0r y0ur f0rum. F0r 1nst4nc3, 4 f0rum 0f 4 n3ws s1t3, m1ght w4nt 4 r3l4t1v3ly h1gh v4lu3 f0r \'4g3 0f l4st m4tch1ng m3ss4g3\'. 4ll v4lu3s 4r3 r3l4t1v3 1n r3l4t10n t0 34ch 0th3r 4nd sh0uld b3 p0s1t1v3 1nt3g3rs.<br /><br />Th1s f4ct0r c0unts th3 4m0unt 0f m4tch1ng m3ss4g3s 4nd d1v1d3s th3m by th3 t0t4l numb3r 0f m3ss4g3s w1th1n 4 t0p1c.';
$helptxt['search_weight_age'] = 'W31ght f4ct0rs 4r3 us3d t0 d3t3rm1n3 th3 r3l3v4ncy 0f 4 s34rch r3sult. Ch4ng3 th3s3 w31ght f4ct0rs t0 m4tch th3 th1ngs th4t 4r3 sp3c1f1c4lly 1mp0rt4nt f0r y0ur f0rum. F0r 1nst4nc3, 4 f0rum 0f 4 n3ws s1t3, m1ght w4nt 4 r3l4t1v3ly h1gh v4lu3 f0r \'4g3 0f l4st m4tch1ng m3ss4g3\'. 4ll v4lu3s 4r3 r3l4t1v3 1n r3l4t10n t0 34ch 0th3r 4nd sh0uld b3 p0s1t1v3 1nt3g3rs.<br /><br />Th1s f4ct0r r4t3s th3 4g3 0f th3 l4st m4tch1ng m3ss4g3 w1th1n 4 t0p1c. Th3 m0r3 r3c3nt th1s m3ss4g3 1s, th3 h1gh3r th3 sc0r3.';
$helptxt['search_weight_length'] = 'W31ght f4ct0rs 4r3 us3d t0 d3t3rm1n3 th3 r3l3v4ncy 0f 4 s34rch r3sult. Ch4ng3 th3s3 w31ght f4ct0rs t0 m4tch th3 th1ngs th4t 4r3 sp3c1f1c4lly 1mp0rt4nt f0r y0ur f0rum. F0r 1nst4nc3, 4 f0rum 0f 4 n3ws s1t3, m1ght w4nt 4 r3l4t1v3ly h1gh v4lu3 f0r \'4g3 0f l4st m4tch1ng m3ss4g3\'. 4ll v4lu3s 4r3 r3l4t1v3 1n r3l4t10n t0 34ch 0th3r 4nd sh0uld b3 p0s1t1v3 1nt3g3rs.<br /><br />Th1s f4ct0r 1s b4s3d 0n th3 t0p1c s1z3. Th3 m0r3 m3ss4g3s 4r3 w1th1n th3 t0p1c, th3 h1gh3r th3 sc0r3.';
$helptxt['search_weight_subject'] = 'W31ght f4ct0rs 4r3 us3d t0 d3t3rm1n3 th3 r3l3v4ncy 0f 4 s34rch r3sult. Ch4ng3 th3s3 w31ght f4ct0rs t0 m4tch th3 th1ngs th4t 4r3 sp3c1f1c4lly 1mp0rt4nt f0r y0ur f0rum. F0r 1nst4nc3, 4 f0rum 0f 4 n3ws s1t3, m1ght w4nt 4 r3l4t1v3ly h1gh v4lu3 f0r \'4g3 0f l4st m4tch1ng m3ss4g3\'. 4ll v4lu3s 4r3 r3l4t1v3 1n r3l4t10n t0 34ch 0th3r 4nd sh0uld b3 p0s1t1v3 1nt3g3rs.<br /><br />Th1s f4ct0r l00ks wh3th3r 4 s34rch t3rm c4n b3 f0und w1th1n th3 subj3ct 0f 4 t0p1c.';
$helptxt['search_weight_first_message'] = 'W31ght f4ct0rs 4r3 us3d t0 d3t3rm1n3 th3 r3l3v4ncy 0f 4 s34rch r3sult. Ch4ng3 th3s3 w31ght f4ct0rs t0 m4tch th3 th1ngs th4t 4r3 sp3c1f1c4lly 1mp0rt4nt f0r y0ur f0rum. F0r 1nst4nc3, 4 f0rum 0f 4 n3ws s1t3, m1ght w4nt 4 r3l4t1v3ly h1gh v4lu3 f0r \'4g3 0f l4st m4tch1ng m3ss4g3\'. 4ll v4lu3s 4r3 r3l4t1v3 1n r3l4t10n t0 34ch 0th3r 4nd sh0uld b3 p0s1t1v3 1nt3g3rs.<br /><br />Th1s f4ct0r l00ks wh3th3r 4 m4tch c4n b3 f0und 1n th3 f1rst m3ss4g3 0f 4 t0p1c.';
$helptxt['search_weight_sticky'] = 'W31ght f4ct0rs 4r3 us3d t0 d3t3rm1n3 th3 r3l3v4ncy 0f 4 s34rch r3sult. Ch4ng3 th3s3 w31ght f4ct0rs t0 m4tch th3 th1ngs th4t 4r3 sp3c1f1c4lly 1mp0rt4nt f0r y0ur f0rum. F0r 1nst4nc3, 4 f0rum 0f 4 n3ws s1t3, m1ght w4nt 4 r3l4t1v3ly h1gh v4lu3 f0r \'4g3 0f l4st m4tch1ng m3ss4g3\'. 4ll v4lu3s 4r3 r3l4t1v3 1n r3l4t10n t0 34ch 0th3r 4nd sh0uld b3 p0s1t1v3 1nt3g3rs.<br /><br />Th1s f4ct0r l00ks wh3th3r 4 t0p1c 1s st1cky 4nd 1ncr34s3s th3 r3l3v4ncy sc0r3 1f 1t 1s.';
$helptxt['search'] = '4djust 4ll s3tt1ngs f0r th3 s34rch funct10n h3r3.';
$helptxt['search_why_use_index'] = '4 s34rch 1nd3x c4n gr34tly 1mpr0v3 th3 p3rf0rm4nc3 0f s34rch3s 0n y0ur f0rum. 3sp3c14lly wh3n th3 numb3r 0f m3ss4g3s 0n 4 f0rum gr0ws b1gg3r, s34rch1ng w1th0ut 4n 1nd3x c4n t4k3 4 l0ng t1m3 4nd 1ncr34s3 th3 pr3ssur3 0n y0ur d4t4b4s3. 1f y0ur f0rum 1s b1gg3r th4n 50.000 m3ss4g3s, y0u m1ght w4nt t0 c0ns1d3r cr34t1ng 4 s34rch 1nd3x t0 4ssur3 p34k p3rf0rm4nc3 0f y0ur f0rum.<br /><br />N0t3 th4t 4 s34rch 1nd3x c4n t4k3 up qu1t3 s0m3 sp4c3. 4 fullt3xt 1nd3x 1s 4 bu1lt-1n 1nd3x 0f MySQL. 1t\'s r3l4t1v3ly c0mp4ct (4ppr0x1m4t3ly th3 s4m3 s1z3 4s th3 m3ss4g3 t4bl3), but 4 l0t 0f w0rds 4r3n\'t 1nd3x3d 4nd 1t c4n, 1n s0m3 s34rch qu3r13s, turn 0ut t0 b3 v3ry sl0w. Th3 cust0m 1nd3x 1s 0ft3n b1gg3r (d3p3nd1ng 0n y0ur c0nf1gur4t10n 1t c4n b3 up t0 3 t1m3s th3 s1z3 0f th3 m3ss4g3s t4bl3) but 1t\'s p3rf0rm4nc3 1s b3tt3r th4n fullt3xt 4nd r3l4t1v3ly st4bl3.';
$helptxt['see_admin_ip'] = '1P 4ddr3ss3s 4r3 sh0wn t0 4dm1n1str4t0rs 4nd m0d3r4t0rs t0 f4c1l1t4t3 m0d3r4t10n 4nd t0 m4k3 1t 34s13r t0 tr4ck p30pl3 up t0 n0 g00d.  R3m3mb3r th4t 1P 4ddr3ss3s m4y n0t 4lw4ys b3 1d3nt1fy1ng, 4nd m0st p30pl3\'s 1P 4ddr3ss3s ch4ng3 p3r10d1c4lly.<br /><br />M3mb3rs 4r3 4ls0 4ll0w3d t0 s33 th31r 0wn 1Ps.';
$helptxt['see_member_ip'] = 'Y0ur 1P 4ddr3ss 1s sh0wn 0nly t0 y0u 4nd m0d3r4t0rs.  R3m3mb3r th4t th1s 1nf0rm4t10n 1s n0t 1d3nt1fy1ng, 4nd th4t m0st 1Ps ch4ng3 p3r10d1c4lly.<br /><br />Y0u c4nn0t s33 0th3r m3mb3rs\' 1P 4ddr3ss3s, 4nd th3y c4nn0t s33 y0urs.';
$helptxt['whytwoip'] = 'SMF us3s v4r10us m3th0ds t0 d3t3ct us3r 1P 4ddr3ss3s. Usu4lly th3s3 tw0 m3th0ds r3sult 1n th3 s4m3 4ddr3ss but 1n s0m3 c4s3s m0r3 th4n 0n3 4ddr3ss m4y b3 d3t3ct3d. 1n th1s c4s3 SMF l0gs b0th 4ddr3ss3s, 4nd us3s th3m b0th f0r b4n ch3cks (3tc). Y0u c4n cl1ck 0n 31th3r 4ddr3ss t0 tr4ck th4t 1P 4nd b4n 1f n3c3ss4ry.';
$helptxt['ban_cannot_post'] = 'Th3 \'c4nn0t p0st\' r3str1ct10n turns th3 f0rum 1nt0 r34d-0nly m0d3 f0r th3 b4nn3d us3r. Th3 us3r c4nn0t cr34t3 n3w t0p1cs, 0r r3ply t0 3x1st1ng 0n3s, s3nd p3rs0n4l m3ss4g3s 0r v0t3 1n p0lls. Th3 b4nn3d us3r c4n h0w3v3r st1ll r34d p3rs0n4l m3ss4g3s 4nd t0p1cs.<br /><br />4 w4rn1ng m3ss4g3 1s sh0wn t0 th3 us3rs th4t 4r3 b4nn3d th1s w4y.';
$helptxt['posts_and_topics'] = '
	<ul cl4ss=\"n0rm4ll1st\">
		<l1>
			<b>P0st S3tt1ngs</b><br />
			M0d1fy th3 s3tt1ngs r3l4t3d t0 th3 p0st1ng 0f m3ss4g3s 4nd th3 w4y m3ss4g3s 4r3 sh0wn. Y0u c4n 4ls0 3n4bl3 th3 sp3ll ch3ck h3r3.
		</l1><l1>
			<b>Bull3t1n B04rd C0d3</b><br />
			3n4bl3 th3 c0d3 th4t sh0ws f0rum m3ss4g3s 1n th3 r1ght l4y0ut. 4ls0 4djust wh1ch c0d3s 4r3 4ll0w3d 4nd wh1ch 4r3n\'t.
		</l1><l1>
			<b>C3ns0r3d W0rds</b>
			1n 0rd3r t0 k33p th3 l4ngu4g3 0n y0ur f0rum und3r c0ntr0l, y0u c4n c3ns0r c3rt41n w0rds. Th1s funct10n 4ll0ws y0u t0 c0nv3rt f0rb1dd3n w0rds 1nt0 1nn0c3nt v3rs10ns.
		</l1><l1>
			<b>T0p1c S3tt1ngs</b>
			M0d1fy th3 s3tt1ngs r3l4t3d t0 t0p1cs. Th3 numb3r 0f t0p1cs p3r p4g3, wh3th3r st1cky t0p1cs 4r3 3n4bl3d 0r n0t, th3 numb3r 0f m3ss4g3s n33d3d f0r 4 t0p1c t0 b3 h0t, 3tc.
		</l1>
	</ul>';
$helptxt['spider_group'] = 'By s3l3ct1ng 4 r3str1ct1v3 gr0up, wh3n 4 gu3st 1s d3t3ct3d 4s 4 s34rch cr4wl3r 1t w1ll 4ut0m4t1c4lly b3 4ss1gn3d 4ny &qu0t;d3ny&qu0t; d3ny p3rm1ss10ns 0f th1s gr0up 1n 4dd1t10n t0 th3 n0rm4l p3rm1ss10ns 0f 4 gu3st. Y0u c4n us3 th1s t0 pr0v1d3 l3ss3r 4cc3ss t0 4 s34rch 3ng1n3 th4n y0u w0uld 4 n0rm4l gu3st. Y0u m1ght f0r 3x4mpl3 w1sh t0 cr34t3 4 n3w gr0up c4ll3d &qu0t;Sp1d3rs&qu0t; 4nd s3l3ct th4t h3r3. Y0u c0uld th3n d3ny p3rm1ss10n f0r th4t gr0up t0 v13w pr0f1l3s t0 st0p sp1d3rs 1nd3x1ng y0ur m3mb3rs pr0f1l3s.<br />N0t3: Sp1d3r d3t3ct10n 1s n0t p3rf3ct 4nd c4n b3 s1mul4t3d by us3rs s0 th1s f34tur3 1s n0t gu4r4nt33d t0 r3str1ct c0nt3nt 0nly t0 th0s3 s34rch 3ng1n3s y0u h4v3 4dd3d.';
$helptxt['show_spider_online'] = 'Th1s s3tt1ng 4ll0ws y0u t0 s3l3ct wh3th3r sp1d3rs sh0uld b3 l1st3d 1n th3 wh0\'s 0nl1n3 l1st 0n th3 b04rd 1nd3x 4nd &qu0t;Wh0\'s 0nl1n3&qu0t; p4g3. 0pt10ns 4r3:
	<ul cl4ss=\"n0rm4ll1st\">
		<l1>
			<b>N0t 4t 4ll</b><br />
			Sp1d3rs w1ll s1mply 4pp34r 4s gu3sts t0 4ll us3rs.
		</l1><l1>
			<b>Sh0w Sp1d3r Qu4nt1ty</b><br />
			Th3 B04rd 1nd3x w1ll d1spl4y th3 numb3r 0f sp1d3rs curr3ntly v1s1t1ng th3 f0rum.
		</l1><l1>
			<b>Sh0w Sp1d3r N4m3s</b><br />
			34ch sp1d3r n4m3 w1ll b3 r3v34l3d, s0 us3rs c4n s33 h0w m4ny 0f 34ch sp1d3r 1s curr3ntly v1s1t1ng th3 f0rum - th1s t4k3s 3ff3ct 1n b0th th3 B04rd 1nd3x 4nd Wh0\'s 0nl1n3 p4g3.
		</l1><l1>
			<b>Sh0w Sp1d3r N4m3s - 4dm1n 0nly</b><br />
			4s 4b0v3 3xc3pt 0nly 4dm1n1str4t0rs c4n s33 sp1d3r st4tus - t0 4ll 0th3r us3rs sp1d3rs 4pp34r 4s gu3sts.
		</l1>
	</ul>';
$helptxt['birthday_email'] = 'Ch00s3 th3 1nd3x 0f th3 b1rthd4y 3m41l m3ss4g3 t0 us3.  4 pr3v13w w1ll b3 sh0wn 1n th3 3m41l Subj3ct 4nd 3m41l B0dy f13lds.<br /><str0ng>N0t3:</str0ng> S3tt1ng th1s 0pt10n d03s n0t 4ut0m4t1c4lly 3n4bl3 b1rthd4y 3m41ls.  T0 3n4bl3 b1rthd4y 3m41ls us3 th3 <4 hr3f=\"%1$s?4ct10n=4dm1n;4r34=m41nt41n;s4=t4sks;s3sc=%2$s\" t4rg3t=\"_bl4nk\" cl4ss=\"n3w_w1n\">Sch3dul3d T4sks</4> p4g3 4nd 3n4bl3 th3 b1rthd4y 3m41l t4sk.';
$helptxt['pm_bcc'] = 'Wh3n s3nd1ng 4 p3rs0n4l m3ss4g3 y0u c4n ch00s3 t0 4dd 4 r3c1p13nt 4s BCC 0r &qu0t;Bl1nd C4rb0n C0py&qu0t;. BCC r3c1p13nts d0 n0t h4v3 th31r 1d3nt1t13s r3v34l3d t0 0th3r r3c1p13nts 0f th3 m3ss4g3.';
$helptxt['move_topics_maintenance'] = 'Th1s w1ll 4ll0w y0u t0 m0v3 4ll th3 p0sts fr0m 0n3 b04rd t0 4n0th3r b04rd.';
$helptxt['maintain_reattribute_posts'] = 'Y0u c4n us3 th1s funct10n t0 4ttr1but3 gu3st p0sts 0n y0ur b04rd t0 4 r3g1st3r3d m3mb3r. Th1s 1s us3ful 1f, f0r 3x4mpl3, 4 us3r d3l3t3d th31r 4cc0unt 4nd ch4ng3d th31r m1nd 4nd w1sh3d t0 h4v3 th31r 0ld p0sts 4ss0c14t3d w1th th31r 4cc0unt.';
$helptxt['chmod_flags'] = 'Y0u c4n m4nu4lly s3t th3 p3rm1ss10ns y0u w1sh t0 s3t th3 s3l3ct3d f1l3s t0. T0 d0 th1s 3nt3r th3 chm0d v4lu3 4s 4 num3r1c (0ct3t) v4lu3. N0t3 - th3s3 fl4gs w1ll h4v3 n0 3ff3ct 0n M1cr0s0ft W1nd0ws 0p3r4t1ng syst3ms.';

?>