<?php
			   		 
//ManageCalendar.english.php
// Generated by vbgamer45 http://www.smfhacks.com
$txt['calendar_desc'] = 'Fr0m h3r3 y0u c4n m0d1fy 4ll 4sp3cts 0f th3 c4l3nd4r.';
$txt['calendar_settings_desc'] = 'H3r3 y0u c4n 3n4bl3 th3 c4l3nd4r, 4nd d3t3rm1n3 th3 s3tt1ngs th4t 1t sh0uld us3.';
$txt['save_settings'] = 'S4v3 S3tt1ngs';
$txt['groups_calendar_view'] = 'M3mb3rgr0ups 4ll0w3d t0 v13w th3 c4l3nd4r';
$txt['groups_calendar_post'] = 'M3mb3rgr0ups 4ll0w3d t0 cr34t3 3v3nts';
$txt['groups_calendar_edit_own'] = 'M3mb3rgr0ups 4ll0w3d t0 3d1t th31r 0wn 3v3nts';
$txt['groups_calendar_edit_any'] = 'M3mb3rgr0ups 4ll0w3d t0 3d1t 4ny 3v3nts';
$txt['setting_cal_enabled'] = '3n4bl3 th3 c4l3nd4r';
$txt['setting_cal_daysaslink'] = 'Sh0w d4ys 4s l1nks t0 \'P0st 3v3nt\'';
$txt['setting_cal_showweeknum'] = 'Sh0w w33k numb3rs';
$txt['setting_cal_days_for_index'] = 'M4x d4ys 1n 4dv4nc3 0n b04rd 1nd3x';
$txt['setting_cal_showholidays'] = 'Sh0w h0l1d4ys';
$txt['setting_cal_showbdays'] = 'Sh0w b1rthd4ys';
$txt['setting_cal_showevents'] = 'Sh0w 3v3nts';
$txt['setting_cal_show_never'] = 'N3v3r';
$txt['setting_cal_show_cal'] = '1n c4l3nd4r 0nly';
$txt['setting_cal_show_index'] = '0n b04rd 1nd3x 0nly';
$txt['setting_cal_show_all'] = '0n b04rd 1nd3x 4nd c4l3nd4r';
$txt['setting_cal_defaultboard'] = 'D3f4ult b04rd t0 p0st 3v3nts 1n';
$txt['setting_cal_allow_unlinked'] = '4ll0w 3v3nts n0t l1nk3d t0 p0sts';
$txt['setting_cal_minyear'] = 'M1n1mum y34r';
$txt['setting_cal_maxyear'] = 'M4x1mum y34r';
$txt['setting_cal_allowspan'] = '4ll0w 3v3nts t0 sp4n mult1pl3 d4ys';
$txt['setting_cal_maxspan'] = 'M4x numb3r 0f d4ys 4n 3v3nt c4n sp4n';
$txt['setting_cal_showInTopic'] = 'Sh0w l1nk3d 3v3nts 1n t0p1c d1spl4y';
$txt['manage_holidays_desc'] = 'Fr0m h3r3 y0u c4n 4dd 4nd r3m0v3 h0l1d4ys fr0m y0ur f0rum c4l3nd4r.';
$txt['current_holidays'] = 'Curr3nt H0l1d4ys';
$txt['holidays_title'] = 'H0l1d4y';
$txt['holidays_title_label'] = 'T1tl3';
$txt['holidays_delete_confirm'] = '4r3 y0u sur3 y0u w1sh t0 r3m0v3 th3s3 h0l1d4ys?';
$txt['holidays_add'] = '4dd N3w H0l1d4y';
$txt['holidays_edit'] = '3d1t 3x1st1ng H0l1d4y';
$txt['holidays_button_add'] = '4dd';
$txt['holidays_button_edit'] = '3d1t';
$txt['holidays_button_remove'] = 'R3m0v3';
$txt['every_year'] = '3v3ry Y34r';

?>