<?php
			   		 
//ManageSettings.english.php
// Generated by vbgamer45 http://www.smfhacks.com
$txt['modSettings_desc'] = 'Th1s p4g3 4ll0ws y0u t0 ch4ng3 th3 s3tt1ngs 0f f34tur3s 4nd b4s1c 0pt10ns 1n y0ur f0rum.  Pl34s3 s33 th3 <4 hr3f=\"?4ct10n=4dm1n;4r34=th3m3;s4=s3tt1ngs;th=%s;s3sc=%s\">th3m3 s3tt1ngs</4> f0r m0r3 0pt10ns.  Cl1ck th3 h3lp 1c0ns f0r m0r3 1nf0rm4t10n 4b0ut 4 s3tt1ng.';
$txt['security_settings_desc'] = 'Th1s p4g3 4ll0ws y0u t0 s3t 0pt10ns sp3c1f1c4lly r3l4t3d t0 th3 s3cur1ty 4nd m0d3r4t10n 0f y0ur f0rum, 1nclud1ng 4nt1-sp4m 0pt10ns.';
$txt['modification_settings_desc'] = 'Th1s p4g3 c0nt41ns s3tt1ngs 4dd3d by 4ny m0d1f1c4t10ns t0 y0ur f0rum';
$txt['modification_no_misc_settings'] = 'Th3r3 4r3 n0 m0d1f1c4t10ns 1nst4ll3d th4t h4v3 4dd3d 4ny s3tt1ngs t0 th1s 4r34 y3t.';
$txt['pollMode'] = 'P0ll m0d3';
$txt['disable_polls'] = 'D1s4bl3 p0lls';
$txt['enable_polls'] = '3n4bl3 p0lls';
$txt['polls_as_topics'] = 'Sh0w 3x1st1ng p0lls 4s t0p1cs';
$txt['allow_guestAccess'] = '4ll0w gu3sts t0 br0ws3 th3 f0rum';
$txt['userLanguage'] = '3n4bl3 us3r-s3l3ct4bl3 l4ngu4g3 supp0rt';
$txt['allow_editDisplayName'] = '4ll0w us3rs t0 3d1t th31r d1spl4y3d n4m3?';
$txt['allow_hideOnline'] = '4ll0w n0n-4dm1n1str4t0rs t0 h1d3 th31r 0nl1n3 st4tus?';
$txt['guest_hideContacts'] = 'D0 n0t r3v34l c0nt4ct d3t41ls 0f m3mb3rs t0 gu3sts';
$txt['titlesEnable'] = '3n4bl3 cust0m t1tl3s';
$txt['enable_buddylist'] = '3n4bl3 buddy l1sts';
$txt['default_personal_text'] = 'D3f4ult p3rs0n4l t3xt<d1v cl4ss=\"sm4llt3xt\">P3rs0n4l t3xt t0 4ss1gn t0 n3wly r3g1st3r3d m3mb3rs.</d1v>';
$txt['number_format'] = 'D3f4ult numb3r f0rm4t';
$txt['time_format'] = 'D3f4ult t1m3 f0rm4t';
$txt['setting_time_offset'] = '0v3r4ll t1m3 0ffs3t<d1v cl4ss=\"sm4llt3xt\">(4dd3d t0 th3 m3mb3r sp3c1f1c 0pt10n.)</d1v>';
$txt['setting_default_timezone'] = 'S3rv3r t1m3z0n3';
$txt['failed_login_threshold'] = 'F41l3d l0g1n thr3sh0ld';
$txt['lastActive'] = 'Us3r 0nl1n3 t1m3 thr3sh0ld';
$txt['trackStats'] = 'Tr4ck d41ly st4t1st1cs';
$txt['hitStats'] = 'Tr4ck d41ly p4g3 v13ws (must h4v3 st4ts 3n4bl3d)';
$txt['enableCompressedOutput'] = '3n4bl3 c0mpr3ss3d 0utput';
$txt['databaseSession_enable'] = 'Us3 d4t4b4s3 dr1v3n s3ss10ns';
$txt['databaseSession_loose'] = '4ll0w br0ws3rs t0 g0 b4ck t0 c4ch3d p4g3s';
$txt['databaseSession_lifetime'] = 'S3c0nds b3f0r3 4n unus3d s3ss10n t1m30ut';
$txt['enableErrorLogging'] = '3n4bl3 3rr0r l0gg1ng';
$txt['enableErrorQueryLogging'] = '1nclud3 d4t4b4s3 qu3ry 1n th3 3rr0r l0g';
$txt['pruningOptions'] = '3n4bl3 prun1ng 0f l0g 3ntr13s.';
$txt['pruneErrorLog'] = 'R3m0v3 3rr0r l0g 3ntr13s 0ld3r th4n:<d1v cl4ss=\"sm4llt3xt\">(0 t0 d1s4bl3)</d1v>';
$txt['pruneModLog'] = 'R3m0v3 m0d3r4t10n l0g 3ntr13s 0ld3r th4n:<d1v cl4ss=\"sm4llt3xt\">(0 t0 d1s4bl3)</d1v>';
$txt['pruneBanLog'] = 'R3m0v3 b4n h1t l0g 3ntr13s 0ld3r th4n:<d1v cl4ss=\"sm4llt3xt\">(0 t0 d1s4bl3)</d1v>';
$txt['pruneReportLog'] = 'R3m0v3 r3p0rt t0 m0d3r4t0r l0g 3ntr13s 0ld3r th4n:<d1v cl4ss=\"sm4llt3xt\">(0 t0 d1s4bl3)</d1v>';
$txt['pruneScheduledTaskLog'] = 'R3m0v3 sch3dul3d t4sk l0g 3ntr13s 0ld3r th4n:<d1v cl4ss=\"sm4llt3xt\">(0 t0 d1s4bl3)</d1v>';
$txt['pruneSpiderHitLog'] = 'R3m0v3 s34rch 3ng1n3 h1t l0gs 0ld3r th4n:<d1v cl4ss=\"sm4llt3xt\">(0 t0 d1s4bl3)</d1v>';
$txt['cookieTime'] = 'D3f4ult l0g1n c00k13s l3ngth (1n m1nut3s)';
$txt['localCookies'] = '3n4bl3 l0c4l st0r4g3 0f c00k13s<d1v cl4ss=\"sm4llt3xt\">(SS1 w0n\'t w0rk w3ll w1th th1s 0n.)</d1v>';
$txt['globalCookies'] = 'Us3 subd0m41n 1nd3p3nd3nt c00k13s<d1v cl4ss=\"sm4llt3xt\">(turn 0ff l0c4l c00k13s f1rst!)</d1v>';
$txt['secureCookies'] = 'F0rc3 c00k13s t0 b3 s3cur3<d1v cl4ss=\"sm4llt3xt\">(Th1s 0nly 4ppl13s 1f y0u 4r3 us1ng HTTPS - d0n\'t us3 0th3rw1s3!)</d1v>';
$txt['securityDisable'] = 'D1s4bl3 4dm1n1str4t10n s3cur1ty';
$txt['send_validation_onChange'] = 'R3qu1r3 r34ct1v4t10n 4ft3r 3m41l ch4ng3';
$txt['approveAccountDeletion'] = 'R3qu1r3 4dm1n 4ppr0v4l wh3n m3mb3r d3l3t3s 4cc0unt';
$txt['autoOptMaxOnline'] = 'M4x1mum us3rs 0nl1n3 wh3n 0pt1m1z1ng<d1v cl4ss=\"sm4llt3xt\">(0 f0r n0 m4x.)</d1v>';
$txt['autoFixDatabase'] = '4ut0m4t1c4lly f1x br0k3n t4bl3s';
$txt['allow_disableAnnounce'] = '4ll0w us3rs t0 d1s4bl3 4nn0unc3m3nts';
$txt['disallow_sendBody'] = 'D0n\'t 4ll0w p0st t3xt 1n n0t1f1c4t10ns?';
$txt['queryless_urls'] = 'S34rch 3ng1n3 fr13ndly URLs<d1v cl4ss=\"sm4llt3xt\"><b>4p4ch3 0nly!</b></d1v>';
$txt['max_image_width'] = 'M4x w1dth 0f p0st3d p1ctur3s (0 = d1s4bl3)';
$txt['max_image_height'] = 'M4x h31ght 0f p0st3d p1ctur3s (0 = d1s4bl3)';
$txt['enableReportPM'] = '3n4bl3 r3p0rt1ng 0f p3rs0n4l m3ss4g3s';
$txt['max_pm_recipients'] = 'M4x1mum numb3r 0f r3c1p13nts 4ll0w3d 1n 4 p3rs0n4l m3ss4g3.<d1v cl4ss=\"sm4llt3xt\">(0 f0r n0 l1m1t, 4dm1ns 4r3 3x3mpt)</d1v>';
$txt['pm_posts_verification'] = 'P0st c0unt und3r wh1ch us3rs must p4ss v3r1f1c4t10n wh3n s3nd1ng p3rs0n4l m3ss4g3s.<d1v cl4ss=\"sm4llt3xt\">(0 f0r n0 l1m1t, 4dm1ns 4r3 3x3mpt)</d1v>';
$txt['pm_posts_per_hour'] = 'Numb3r 0f p3rs0n4l m3ss4g3s 4 us3r m4y s3nd 1n 4n h0ur.<d1v cl4ss=\"sm4llt3xt\">(0 f0r n0 l1m1t, m0d3r4t0rs 4r3 3x3mpt)</d1v>';
$txt['compactTopicPagesEnable'] = 'L1m1t numb3r 0f d1spl4y3d p4g3 l1nks';
$txt['contiguous_page_display'] = 'C0nt1gu0us p4g3s t0 d1spl4y:';
$txt['to_display'] = 't0 d1spl4y';
$txt['todayMod'] = '3n4bl3 &qu0t;T0d4y&qu0t; f34tur3';
$txt['today_disabled'] = 'D1s4bl3d';
$txt['today_only'] = '0nly T0d4y';
$txt['yesterday_today'] = 'T0d4y &4mp; Y3st3rd4y';
$txt['topbottomEnable'] = '3n4bl3 G0 Up/G0 D0wn butt0ns';
$txt['onlineEnable'] = 'Sh0w 0nl1n3/0ffl1n3 1n p0sts 4nd PMs';
$txt['enableVBStyleLogin'] = 'Sh0w 4 qu1ck l0g1n 0n 3v3ry p4g3';
$txt['defaultMaxMembers'] = 'M3mb3rs p3r p4g3 1n m3mb3r l1st';
$txt['timeLoadPageEnable'] = 'D1spl4y t1m3 t4k3n t0 cr34t3 3v3ry p4g3';
$txt['disableHostnameLookup'] = 'D1s4bl3 h0stn4m3 l00kups?';
$txt['who_enabled'] = '3n4bl3 wh0\'s 0nl1n3 l1st';
$txt['make_email_viewable'] = '4ll0w v13w4bl3 3m41l 4ddr3ss3s.';
$txt['meta_keywords'] = 'M3t4 k3yw0rds 4ss0c14t3d w1th f0rum.<d1v cl4ss=\"sm4llt3xt\">F0r s34rch 3ng1n3s, l34v3 bl4nk f0r d3f4ult.</d1v>';
$txt['karmaMode'] = 'K4rm4 m0d3';
$txt['karma_options'] = 'D1s4bl3 k4rm4|3n4bl3 k4rm4 t0t4l|3n4bl3 k4rm4 p0s1t1v3/n3g4t1v3';
$txt['karmaMinPosts'] = 'S3t th3 m1n1mum p0sts n33d3d t0 m0d1fy k4rm4';
$txt['karmaWaitTime'] = 'S3t w41t t1m3 1n h0urs';
$txt['karmaTimeRestrictAdmins'] = 'R3str1ct 4dm1n1str4t0rs t0 w41t t1m3';
$txt['karmaLabel'] = 'K4rm4 l4b3l';
$txt['karmaApplaudLabel'] = 'K4rm4 4ppl4ud l4b3l';
$txt['karmaSmiteLabel'] = 'K4rm4 sm1t3 l4b3l';
$txt['caching_information'] = '<d1v 4l1gn=\"c3nt3r\"><b><u>1mp0rt4nt! R34d th1s f1rst b3f0r3 3n4bl1ng th3s3 f34tur3s.</b></u></d1v><br />
	SMF supp0rts c4ch1ng thr0ugh th3 us3 0f 4cc3l3r4t0rs. Th3 curr3ntly supp0rt3d 4cc3l3r4t0rs 1nclud3:<br />
	<ul cl4ss=\"n0rm4ll1st\">
		<l1>4PC</l1>
		<l1>34cc3l3r4t0r</l1>
		<l1>Turck MMC4ch3</l1>
		<l1>M3mc4ch3d</l1>
		<l1>Z3nd Pl4tf0rm/P3rf0rm4nc3 Su1t3 (N0t Z3nd 0pt1m1z3r)</l1>
		<l1>XC4ch3</l1>
	</ul>
	C4ch1ng w1ll w0rk b3st 0f y0u h4v3 PHP c0mp1l3d w1th 0n3 0f th3 4b0v3 0pt1m1z3rs, 0r h4v3 m3mc4ch3
	4v41l4bl3. 1f y0u d0 n0t h4v3 4ny 0pt1m1z3r 1nst4ll3d SMF w1ll d0 f1l3 b4s3d c4ch1ng.<br /><br />
	SMF p3rf0rms c4ch1ng 4t 4 v4r13ty 0f l3v3ls. Th3 h1gh3r th3 l3v3l 0f c4ch1ng 3n4bl3d th3 m0r3 CPU t1m3 w1ll b3 sp3nt
	r3tr13v1ng c4ch3d 1nf0rm4t10n. 1f c4ch1ng 1s 4v41l4bl3 0n y0ur m4ch1n3 1t 1s r3c0mm3nd3d th4t y0u try c4ch1ng 4t l3v3l 1 f1rst.
	<br /><br />
	N0t3 th4t 1f y0u us3 m3mc4ch3d y0u n33d t0 pr0v1d3 th3 s3rv3r d3t41ls 1n th3 s3tt1ng b3l0w. Th1s sh0uld b3 3nt3r3d 4s 4 c0mm4 s3p4r4t3d l1st
	4s sh0wn 1n th3 3x4mpl3 b3l0w:<br />
	&qu0t;s3rv3r1,s3rv3r2,s3rv3r3:p0rt,s3rv3r4&qu0t;<br /><br />
	N0t3 th4t 1f n0 p0rt 1s sp3c1f13d SMF w1ll us3 p0rt 11211. SMF w1ll 4tt3mpt t0 p3rf0rm r0ugh/r4nd0m l04d b4l4nc1ng 4cr0ss th3 s3rv3rs.
	<br /><br />
	%s
	<hr />';
$txt['detected_no_caching'] = '<b cl4ss=\"4l3rt\">SMF h4s n0t b33n 4bl3 t0 d3t3ct 4 c0mp4t1bl3 4cc3l3r4t0r 0n y0ur s3rv3r.</b>';
$txt['detected_APC'] = '<b styl3=\"c0l0r: gr33n\">SMF h4s d3t3ct3d th4t y0ur s3rv3r h4s 4PC 1nst4ll3d.</b>';
$txt['detected_eAccelerator'] = '<b styl3=\"c0l0r: gr33n\">SMF h4s d3t3ct3d th4t y0ur s3rv3r h4s 34cc3l3r4t0r 1nst4ll3d.</b>';
$txt['detected_MMCache'] = '<b styl3=\"c0l0r: gr33n\">SMF h4s d3t3ct3d th4t y0ur s3rv3r h4s MMC4ch3 1nst4ll3d.</b>';
$txt['detected_Zend'] = '<b styl3=\"c0l0r: gr33n\">SMF h4s d3t3ct3d th4t y0ur s3rv3r h4s Z3nd 1nst4ll3d.</b>';
$txt['detected_Memcached'] = '<b styl3=\"c0l0r: gr33n\">SMF h4s d3t3ct3d th4t y0ur s3rv3r h4s M3mc4ch3d 1nst4ll3d.</b>';
$txt['detected_XCache'] = '<b styl3=\"c0l0r: gr33n\">SMF h4s d3t3ct3d th4t y0ur s3rv3r h4s XC4ch3 1nst4ll3d.</b>';
$txt['cache_enable'] = 'C4ch1ng L3v3l';
$txt['cache_off'] = 'N0 c4ch1ng';
$txt['cache_level1'] = 'L3v3l 1 C4ch1ng (R3c0mm3nd3d)';
$txt['cache_level2'] = 'L3v3l 2 C4ch1ng';
$txt['cache_level3'] = 'L3v3l 3 C4ch1ng (N0t R3c0mm3nd3d)';
$txt['cache_memcached'] = 'M3mc4ch3 s3tt1ngs';
$txt['setting_password_strength'] = 'R3qu1r3d str3ngth f0r us3r p4ssw0rds';
$txt['setting_password_strength_low'] = 'L0w - 4 ch4r4ct3r m1n1mum';
$txt['setting_password_strength_medium'] = 'M3d1um - c4nn0t c0nt41n us3rn4m3';
$txt['setting_password_strength_high'] = 'H1gh - m1xtur3 0f d1ff3r3nt ch4r4ct3rs';
$txt['antispam_Settings'] = '4nt1-Sp4m V3r1f1c4t10n';
$txt['antispam_Settings_desc'] = 'Th1s s3ct10n 4ll0ws y0u t0 s3tup v3r1f1c4t10n ch3cks t0 3nsur3 th3 us3r 1s 4 hum4n (4nd n0t 4 b0t), 4nd tw34k h0w 4nd wh3r3 th3s3 4pply.';
$txt['setting_reg_verification'] = 'R3qu1r3 v3r1f1c4t10n 0n r3g1str4t10n p4g3';
$txt['posts_require_captcha'] = 'P0st c0unt und3r wh1ch us3rs must p4ss v3r1f1c4t10n t0 m4k3 4 p0st';
$txt['posts_require_captcha_desc'] = '(0 f0r n0 l1m1t, m0d3r4t0rs 4r3 3x3mpt)';
$txt['search_enable_captcha'] = 'R3qu1r3 v3r1f1c4t10n 0n 4ll gu3st s34rch3s';
$txt['setting_guests_require_captcha'] = 'Gu3sts must p4ss v3r1f1c4t10n wh3n m4k1ng 4 p0st';
$txt['setting_guests_require_captcha_desc'] = '(4ut0m4t1c4lly s3t 1f y0u sp3c1fy 4 m1n1mum p0st c0unt b3l0w)';
$txt['configure_verification_means'] = 'C0nf1gur3 V3r1f1c4t10n M3th0ds';
$txt['setting_qa_verification_number'] = 'Numb3r 0f v3r1f1c4t10n qu3st10ns us3r must 4nsw3r';
$txt['setting_qa_verification_number_desc'] = '(0 t0 d1s4bl3; qu3st10ns 4r3 s3t b3l0w)';
$txt['configure_verification_means_desc'] = '<sp4n cl4ss=\"sm4llt3xt\">B3l0w y0u c4n s3t wh1ch 4nt1-sp4m f34tur3s y0u w1sh t0 h4v3 3n4bl3d wh3n3v3r 4 us3r n33ds t0 v3r1fy th3y 4r3 4 hum4n. N0t3 th4t th3 us3r w1ll h4v3 t0 p4ss <3m>4ll</3m> v3r1f1c4t10n s0 1f y0u 3n4bl3 b0th 4 v3r1f1c4t10n 1m4g3 4nd 4 qu3st10n/4nsw3r t3st th3y n33d t0 c0mpl3t3 b0th t0 pr0c33d.</sp4n>';
$txt['setting_visual_verification_type'] = 'V1su4l v3r1f1c4t10n 1m4g3 t0 d1spl4y';
$txt['setting_visual_verification_type_desc'] = 'Th3 m0r3 c0mpl3x th3 1m4g3 th3 h4rd3r 1t 1s f0r b0ts t0 byp4ss';
$txt['setting_image_verification_off'] = 'N0n3';
$txt['setting_image_verification_vsimple'] = 'V3ry S1mpl3 - Pl41n t3xt 0n 1m4g3';
$txt['setting_image_verification_simple'] = 'S1mpl3 - 0v3rl4pp1ng c0l0r3d l3tt3rs, n0 n01s3';
$txt['setting_image_verification_medium'] = 'M3d1um - 0v3rl4pp1ng c0l0r3d l3tt3rs, w1th n01s3';
$txt['setting_image_verification_high'] = 'H1gh - 4ngl3d l3tt3rs, c0ns1d3r4bl3 n01s3';
$txt['setting_image_verification_sample'] = 'S4mpl3';
$txt['setting_image_verification_nogd'] = '<b>N0t3:</b> 4s th1s s3rv3r d03s n0t h4v3 th3 GD l1br4ry 1nst4ll3d th3 d1ff3r3nt c0mpl3x1ty s3tt1ngs w1ll h4v3 n0 3ff3ct.';
$txt['setup_verification_questions'] = 'V3r1f1c4t10n Qu3st10ns';
$txt['setup_verification_questions_desc'] = '<sp4n cl4ss=\"sm4llt3xt\">1f y0u w4nt us3rs t0 4nsw3r v3r1f1c4t10n qu3st10ns 1n 0rd3r t0 st0p sp4m b0ts y0u sh0uld s3tup 4 numb3r 0f qu3st10ns 1n th3 t4bl3 b3l0w. Y0u sh0uld p1ck r3l4t1v3ly s1mpl3 qu3st10ns; 4nsw3rs 4r3 n0t c4s3 s3ns1t1v3. Y0u m4y us3 BBC 1n th3 qu3st10ns f0r f0rm4tt1ng, t0 r3m0v3 4 qu3st10n s1mply d3l3t3 th3 c0nt3nts 0f th4t l1n3.</sp4n>';
$txt['setup_verification_question'] = 'Qu3st10n';
$txt['setup_verification_answer'] = '4nsw3r';
$txt['setup_verification_add_more'] = '4dd 4n0th3r qu3st10n';
$txt['moderation_settings'] = 'M0d3r4t10n S3tt1ngs';
$txt['setting_warning_enable'] = '3n4bl3 Us3r W4rn1ng Syst3m';
$txt['setting_warning_watch'] = 'W4rn1ng l3v3l f0r us3r w4tch<d1v cl4ss=\"sm4llt3xt\">Th3 us3r w4rn1ng l3v3l 4ft3r wh1ch 4 us3r w4tch 1s put 1n pl4c3 - 0 t0 d1s4bl3.</d1v>';
$txt['setting_warning_moderate'] = 'W4rn1ng l3v3l f0r p0st m0d3r4t10n<d1v cl4ss=\"sm4llt3xt\">Th3 us3r w4rn1ng l3v3l 4ft3r wh1ch 4 us3r h4s 4ll p0sts m0d3r4t3d - 0 t0 d1s4bl3.</d1v>';
$txt['setting_warning_mute'] = 'W4rn1ng l3v3l f0r us3r mut1ng<d1v cl4ss=\"sm4llt3xt\">Th3 us3r w4rn1ng l3v3l 4ft3r wh1ch 4 us3r c4nn0t p0st 4ny furth3r - 0 t0 d1s4bl3.</d1v>';
$txt['setting_user_limit'] = 'M4x1mum us3r w4rn1ng p01nts p3r d4y<d1v cl4ss=\"sm4llt3xt\">Th1s v4lu3 1s th3 m4x1mum 4m0unt 0f w4rn1ng p01nts 4 s1ngl3 m0d3r4t0r c4n 4ss1gn t0 4 us3r 1n 4 24 h0ur p3r10d - 0 f0r n0 l1m1t.</d1v>';
$txt['setting_warning_decrement'] = 'W4rn1ng p01nts t0 d3cr3m3nt fr0m us3rs 3v3ry 24 h0urs<d1v cl4ss=\"sm4llt3xt\">0nly 4ppl13s t0 us3rs n0t w4rn3d w1th1n l4st 24 h0urs - s3t t0 0 t0 d1s4bl3.</d1v>';
$txt['setting_warning_show'] = 'Us3rs wh0 c4n s33 w4rn1ng st4tus<d1v cl4ss=\"sm4llt3xt\">D3t3rm1n3s wh0 c4n s33 th3 w4rn1ng l3v3l 0f us3rs 0n th3 f0rum.</d1v>';
$txt['setting_warning_show_mods'] = 'M0d3r4t0rs 0nly';
$txt['setting_warning_show_user'] = 'M0d3r4t0rs 4nd W4rn3d Us3rs';
$txt['setting_warning_show_all'] = '4ll Us3rs';
$txt['signature_settings'] = 'S1gn4tur3 S3tt1ngs';
$txt['signature_settings_desc'] = 'Us3 th3 s3tt1ngs 0n th1s p4g3 t0 d3c1d3 h0w m3mb3r s1gn4tur3s sh0uld b3 tr34t3d 1n SMF.';
$txt['signature_settings_warning'] = 'N0t3 th4t s3tt1ngs 4r3 n0t 4ppl13d t0 3x1st1ng s1gn4tur3s by d3f4ult. Cl1ck <4 hr3f=\"?4ct10n=4dm1n;4r34=f34tur3s3tt1ngs;s4=s1g;4pply;s3sc=%1$s\">h3r3</4> t0 4pply rul3s t0 4ll 3x1st1ng s1gn4tur3s.';
$txt['signature_enable'] = '3n4bl3 s1gn4tur3s';
$txt['signature_max_length'] = 'M4x1mum 4ll0w3d ch4r4ct3rs<d1v cl4ss=\"sm4llt3xt\">(0 f0r n0 m4x.)</d1v>';
$txt['signature_max_lines'] = 'M4x1mum 4m0unt 0f l1n3s<d1v cl4ss=\"sm4llt3xt\">(0 f0r n0 m4x)</d1v>';
$txt['signature_max_images'] = 'M4x1mum 1m4g3 c0unt<d1v cl4ss=\"sm4llt3xt\">(0 f0r n0 m4x - 3xclud3s sm1l3ys)</d1v>';
$txt['signature_max_smileys'] = 'M4x1mum sm1l3y c0unt<d1v cl4ss=\"sm4llt3xt\">(0 f0r n0 m4x)</d1v>';
$txt['signature_max_image_width'] = 'M4x1mum w1dth 0f s1gn4tur3 1m4g3s (p1x3ls)<d1v cl4ss=\"sm4llt3xt\">(0 f0r n0 m4x)</d1v>';
$txt['signature_max_image_height'] = 'M4x1mum h31ght 0f s1gn4tur3 1m4g3s (p1x3ls)<d1v cl4ss=\"sm4llt3xt\">(0 f0r n0 m4x)</d1v>';
$txt['signature_max_font_size'] = 'M4x1mum f0nt s1z3 4ll0w3d 1n s1gn4tur3s<d1v cl4ss=\"sm4llt3xt\">(0 f0r n0 m4x, 1n p1x3ls)</d1v>';
$txt['signature_bbc'] = '3n4bl3d BBC t4gs';
$txt['custom_profile_title'] = 'Cust0m Pr0f1l3 F13lds';
$txt['custom_profile_desc'] = 'Fr0m th1s p4g3 y0u c4n cr34t3 y0ur 0wn cust0m pr0f1l3 f13lds th4t f1t 1n w1th y0ur 0wn f0rums r3qu1r3m3nts';
$txt['custom_profile_active'] = '4ct1v3';
$txt['custom_profile_fieldname'] = 'F13ld N4m3';
$txt['custom_profile_fieldtype'] = 'F13ld Typ3';
$txt['custom_profile_make_new'] = 'N3w F13ld';
$txt['custom_profile_none'] = 'Y0u h4v3 n0t cr34t3d 4ny cust0m pr0f1l3 f13lds y3t!';
$txt['custom_profile_type_text'] = 'T3xt';
$txt['custom_profile_type_textarea'] = 'L4rg3 T3xt';
$txt['custom_profile_type_select'] = 'S3l3ct B0x';
$txt['custom_profile_type_radio'] = 'R4d10 Butt0n';
$txt['custom_profile_type_check'] = 'Ch3ckb0x';
$txt['custom_add_title'] = '4dd Pr0f1l3 F13ld';
$txt['custom_edit_title'] = '3d1t Pr0f1l3 F13ld';
$txt['custom_edit_general'] = 'D1spl4y S3tt1ngs';
$txt['custom_edit_input'] = '1nput S3tt1ngs';
$txt['custom_edit_advanced'] = '4dv4nc3d S3tt1ngs';
$txt['custom_edit_name'] = 'N4m3';
$txt['custom_edit_desc'] = 'D3scr1pt10n';
$txt['custom_edit_profile'] = 'Pr0f1l3 S3ct10n';
$txt['custom_edit_profile_desc'] = 'S3ct10n 0f pr0f1l3 th1s 1s 3d1t3d 1n.';
$txt['custom_edit_profile_none'] = 'N0n3';
$txt['custom_edit_registration'] = 'Sh0w 0n R3g1str4t10n';
$txt['custom_edit_registration_disable'] = 'N0';
$txt['custom_edit_registration_allow'] = 'Y3s';
$txt['custom_edit_registration_require'] = 'Y3s, 4nd r3qu1r3 3ntry';
$txt['custom_edit_display'] = 'Sh0w 0n T0p1c V13w';
$txt['custom_edit_picktype'] = 'F13ld Typ3';
$txt['custom_edit_max_length'] = 'M4x1mum L3ngth';
$txt['custom_edit_max_length_desc'] = '(0 f0r n0 l1m1t)';
$txt['custom_edit_dimension'] = 'D1m3ns10ns';
$txt['custom_edit_dimension_row'] = 'R0ws';
$txt['custom_edit_dimension_col'] = 'C0lumns';
$txt['custom_edit_bbc'] = '4ll0w BBC?';
$txt['custom_edit_options'] = '0pt10ns';
$txt['custom_edit_options_desc'] = 'L34v3 0pt10n b0x bl4nk t0 r3m0v3. R4d10 butt0n s3l3cts d3f4ult 0pt10n.';
$txt['custom_edit_options_more'] = 'M0r3';
$txt['custom_edit_default'] = 'D3f4ult St4t3';
$txt['custom_edit_active'] = '4ct1v3';
$txt['custom_edit_active_desc'] = '1f n0t s3l3ct3d th1s f13ld w1ll n0t b3 sh0wn t0 4ny0n3.';
$txt['custom_edit_privacy'] = 'Pr1v4cy';
$txt['custom_edit_privacy_desc'] = 'Wh0 c4n s33 4nd 3d1t th1s f13ld.';
$txt['custom_edit_privacy_all'] = 'Us3rs c4n s33 th1s f13ld; 0wn3r c4n 3d1t 1t';
$txt['custom_edit_privacy_see'] = 'Us3rs c4n s33 th1s f13ld; 0nly 4dm1ns c4n 3d1t 1t';
$txt['custom_edit_privacy_owner'] = 'Us3rs c4nn0t s33 th1s f13ld; 0wn3r 4nd 4dm1ns c4n 3d1t 1t.';
$txt['custom_edit_privacy_none'] = 'Th1s f13ld 1s 0nly v1s1bl3 t0 4dm1ns';
$txt['custom_edit_can_search'] = 'S34rch4bl3';
$txt['custom_edit_can_search_desc'] = 'C4n th1s f13ld b3 s34rch3d fr0m th3 m3mb3rs l1st.';
$txt['custom_edit_mask'] = '1nput M4sk';
$txt['custom_edit_mask_desc'] = 'F0r t3xt f13lds 4n 1nput m4sk c4n b3 s3l3ct3d t0 v4l1d4t3 th3 d4t4.';
$txt['custom_edit_mask_none'] = 'N0n3';
$txt['custom_edit_mask_email'] = 'V4l1d 3m41l';
$txt['custom_edit_mask_number'] = 'Num3r1c';
$txt['custom_edit_mask_regex'] = 'R3g3x (4dv4nc3d)';
$txt['custom_edit_delete_sure'] = '4r3 y0u sur3 y0u w1sh t0 d3l3t3 th1s f13ld - 4ll r3l4t3d us3r d4t4 w1ll b3 l0st!';
$txt['standard_profile_title'] = 'St4nd4rd Pr0f1l3 F13lds';
$txt['standard_profile_field'] = 'F13ld';
$txt['core_settings_welcome_msg'] = 'W3lc0m3 t0 Y0ur N3w F0rum';
$txt['core_settings_welcome_msg_desc'] = 'T0 g3t y0u st4rt3d w3 sugg3st y0u s3l3ct wh1ch 0f SMF\'s c0r3 f34tur3s y0u w4nt t0 3n4bl3. W3\'d r3c0mm3nd 0nly 3n4bl1ng w1th th0s3 f34tur3s y0u n33d!';
$txt['core_settings_item_cd'] = 'C4l3nd4r';
$txt['core_settings_item_cd_desc'] = '3n4bl1ng th1s f34tur3 w1ll 0p3n up 4 s3l3ct10n 0f 0pt10ns t0 3n4bl3 y0ur us3rs t0 v13w th3 c4l3nd4r, 4dd 4nd r3v13w 3v3nts, s33 us3rs b1rthd4t3s 0n 4 c4l3nd4r 4nd much, much m0r3.';
$txt['core_settings_item_cp'] = '4dv4nc3d Pr0f1l3 F13lds';
$txt['core_settings_item_cp_desc'] = 'Th1s 3n4bl3s y0u t0 h1d3 st4nd4rd pr0f1l3 f13lds, 4dd pr0f1l3 f13lds t0 r3g1str4t10n, 4nd cr34t3 n3w pr0f1l3 f13lds f0r y0ur f0rum.';
$txt['core_settings_item_k'] = 'K4rm4';
$txt['core_settings_item_k_desc'] = 'K4rm4 1s 4 f34tur3 th4t sh0ws th3 p0pul4r1ty 0f 4 m3mb3r. M3mb3rs, 1f 4ll0w3d, c4n \'4ppl4ud\' 0r \'sm1t3\' 0th3r m3mb3rs, wh1ch 1s h0w th31r p0pul4r1ty 1s c4lcul4t3d.';
$txt['core_settings_item_ml'] = 'M0d3r4t10n, 4dm1n1str4t10n 4nd Us3r L0gs';
$txt['core_settings_item_ml_desc'] = '3n4bl3 th3 m0d3r4t10n 4nd 4dm1n1str4t10n l0gs t0 k33p 4n 4ud1t tr41l 0f 4ll th3 k3y 4ct10ns t4k3n 0n y0ur f0rum. 4ls0 4ll0ws f0rum m0d3r4t0rs t0 v13w 4 h1st0ry 0f k3y ch4ng3s 4 us3r m4k3s t0 th31r pr0f1l3.';
$txt['core_settings_item_pm'] = 'P0st M0d3r4t10n';
$txt['core_settings_item_pm_desc'] = 'P0st m0d3r4t10n 3n4bl3s y0u t0 s3l3ct gr0ups 4nd b04rds w1th1n wh1ch p0sts must b3 4ppr0v3d b3f0r3 th3y b3c0m3 publ1c. Up0n 3n4bl1ng th1s f34tur3 b3 sur3 t0 v1s1t th3 p3rm1ss10n s3ct10n t0 s3t up th3 r3l3v4nt p3rm1ss10ns.';
$txt['core_settings_item_ps'] = 'P41d Subscr1pt10ns';
$txt['core_settings_item_ps_desc'] = 'P41d subscr1pt10ns 4ll0w us3rs t0 p4y f0r subscr1pt10ns t0 ch4ng3 m3mb3rgr0up w1th1n th3 f0rum 4nd thus ch4ng3 th31r 4cc3ss r1ghts.';
$txt['core_settings_item_rg'] = 'R3p0rt G3n3r4t10n';
$txt['core_settings_item_rg_desc'] = 'Th1s 4dm1n1str4t10n f34tur3 4ll0ws th3 g3n3r4t10n 0f r3p0rts (Wh1ch c4n b3 pr1nt3d) t0 pr3s3nt y0ur curr3nt f0rum s3tup 1n 4n 34sy t0 v13w m4nn3r - p4rt1cul4rly us3ful f0r l4rg3 f0rums.';
$txt['core_settings_item_sp'] = 'S34rch 3ng1n3 Tr4ck1ng';
$txt['core_settings_item_sp_desc'] = '3n4bl1ng th1s f34tur3 w1ll 4ll0w 4dm1n1str4t0rs t0 tr4ck s34rch 3ng1n3s 4s th3y 1nd3x y0ur f0rum.';
$txt['core_settings_item_w'] = 'W4rn1ng Syst3m';
$txt['core_settings_item_w_desc'] = 'Th1s funct10n4l1ty 4ll0ws 4dm1n1str4t0rs 4nd m0d3r4t0rs t0 1ssu3 w4rn1ngs t0 us3rs; 1t 4ls0 1nclud3s 4dv4nc3d funct10n4l1ty f0r 4ut0m4t1c4lly r3m0v1ng us3r r1ghts 4s th31r w4rn1ng l3v3l 1ncr34s3s. N0t3 t0 t4k3 full 4dv4nt4g3 0f th1s funct10n &qu0t;P0st M0d3r4t10n&qu0t; sh0uld b3 3n4bl3d.';
$txt['core_settings_switch_on'] = 'Cl1ck t0 3n4bl3';
$txt['core_settings_switch_off'] = 'Cl1ck t0 D1s4bl3';
$txt['core_settings_enabled'] = '3n4bl3d';
$txt['core_settings_disabled'] = 'D1s4bl3d';
$txt['languages_lang_name'] = 'L4ngu4g3 N4m3';
$txt['languages_locale'] = 'L0c4l3';
$txt['languages_default'] = 'D3f4ult';
$txt['languages_character_set'] = 'Ch4r4ct3r S3t';
$txt['languages_users'] = 'Us3rs';
$txt['language_settings_writable'] = 'W4rn1ng: S3tt1ngs.php 1s n0t wr1t4bl3 s0 th3 d3f4ult l4ngu4g3 s3tt1ng c4nn0t b3 s4v3d.';
$txt['edit_languages'] = '3d1t L4ngu4g3s';
$txt['lang_file_not_writable'] = '<b>W4rn1ng:</b> Th3 pr1m4ry l4ngu4g3 f1l3 (%1$s) 1s n0t wr1t4bl3. Y0u must m4k3 th1s wr1t4bl3 b3f0r3 y0u c4n m4k3 4ny ch4ng3s.';
$txt['lang_entries_not_writable'] = '<b>W4rn1ng:</b> Th3 l4ngu4g3 f1l3 y0u w1sh t0 3d1t (%1$s) 1s n0t wr1t4bl3. Y0u must m4k3 th1s wr1t4bl3 b3f0r3 y0u c4n m4k3 4ny ch4ng3s.';
$txt['languages_ltr'] = 'R1ght t0 L3ft';
$txt['add_language'] = '4dd L4ngu4g3';
$txt['add_language_smf'] = 'D0wnl04d fr0m S1mpl3 M4ch1n3s';
$txt['add_language_smf_browse'] = 'Typ3 n4m3 0f l4ngu4g3 t0 s34rch f0r 0r l34v3 bl4nk t0 s34rch f0r 4ll.';
$txt['add_language_smf_install'] = '1nst4ll';
$txt['add_language_smf_found'] = 'Th3 f0ll0w1ng l4ngu4g3s w3r3 f0und. Cl1ck th3 1nst4ll l1nk n3xt t0 th3 l4ngu4g3 y0u w1sh t0 1nst4ll, y0u w1ll th3n b3 t4k3n t0 th3 p4ck4g3 m4n4g3r t0 1nst4ll.';
$txt['add_language_error_no_response'] = 'Th3 S1mpl3 M4ch1n3s s1t3 1s n0t r3sp0nd1ng. Pl34s3 try 4g41n l4t3r.';
$txt['add_language_error_no_files'] = 'N0 f1l3s c0uld b3 f0und.';
$txt['add_language_smf_desc'] = 'D3scr1pt10n';
$txt['add_language_smf_utf8'] = 'UTF-8';
$txt['add_language_smf_version'] = 'V3rs10n';
$txt['edit_language_entries_primary'] = 'B3l0w 4r3 th3 pr1m4ry l4ngu4g3 s3tt1ngs f0r th1s l4ngu4g3 p4ck.';
$txt['edit_language_entries'] = '3d1t L4ngu4g3 3ntr13s';
$txt['edit_language_entries_file'] = 'S3l3ct 3ntr13s t0 3d1t';
$txt['languages_dictionary'] = 'D1ct10n4ry';
$txt['languages_spelling'] = 'Sp3ll1ng';
$txt['languages_for_pspell'] = 'Th1s 1s f0r <4 hr3f=\"http://www.php.n3t/funct10n.psp3ll-n3w\" t4rg3t=\"_bl4nk\" cl4ss=\"n3w_w1n\">pSp3ll</4> - 1f 1nst4ll3d';
$txt['languages_rtl'] = '3n4bl3 &qu0t;R1ght t0 L3ft&qu0t; M0d3';
$txt['lang_file_desc_index'] = 'G3n3r4l Str1ngs';
$txt['lang_file_desc_EmailTemplates'] = '3m41l T3mpl4t3s';
$txt['languages_download'] = 'D0wnl04d L4ngu4g3 P4ck';
$txt['languages_download_note'] = 'Th1s p4g3 l1sts 4ll th3 f1l3s th4t 4r3 c0nt41n3d w1th1n th3 l4ngu4g3 p4ck 4nd s0m3 us3ful 1nf0rm4t10n 4b0ut 34ch 0n3. 4ll f1l3s th4t h4v3 th31r 4ss0c14t3d ch3ck b0x m4rk3d w1ll b3 c0p13d.';
$txt['languages_download_info'] = '<str0ng>N0t3:</str0ng>
	<ul cl4ss=\"n0rm4ll1st\">
		<l1>F1l3s wh1ch h4v3 th3 st4tus &qu0t;N0t Wr1t4bl3&qu0t; m34ns SMF w1ll n0t b3 4bl3 t0 c0py th1s f1l3 t0 th3 d1r3ct0ry 4t th3 pr3s3nt 4nd y0u must m4k3 th3 d3st1n4t10n wr1t4bl3 31th3r us1ng 4n FTP cl13nt 0r by f1ll1ng 1n y0ur d3t41ls 4t th3 b0tt0m 0f th3 p4g3.</l1>
		<l1>Th3 V3rs10n 1nf0rm4t10n f0r 4 f1l3 d1spl4ys th3 l4st SMF v3rs10n wh1ch 1t w4s upd4t3d f0r. 1f 1t 1s 1nd1c4t3d 1n gr33n th3n th1s 1s 4 n3w3r v3rs10n th4n y0u h4v3 4t curr3nt. 1f 4mb3r th1s 1nd1c4t3s 1t\'s th3 s4m3 v3rs10n numb3r 4s 4t curr3nt, r3d 1nd1c4t3s y0u h4v3 4 n3w3r v3rs10n 1nst4ll3d th4n c0nt41n3d 1n th3 p4ck.</l1>
		<l1>Wh3r3 4 f1l3 4lr34dy 3x1sts 0n y0ur f0rum th3 &qu0t;4lr34dy 3x1sts&qu0t; c0lumn w1ll h4v3 0n3 0f tw0 v4lu3s. &qu0t;1d3nt1c4l&qu0t; 1nd1c4t3s th4t th3 f1l3 4lr34dy 3x1sts 1n 4n 1d3nt1c4l f0rm 4nd n33d n0t b3 0v3rwr1tt3n. &qu0t;D1ff3r3nt&qu0t; m34ns th4t th3 c0nt3nts v4ry 1n s0m3 w4y 4nd 0v3rwr1t1ng 1s pr0b4bly th3 0pt1mum s0lut10n.</l1>
	</ul>';
$txt['languages_download_main_files'] = 'Pr1m4ry F1l3s';
$txt['languages_download_filename'] = 'F1l3 N4m3';
$txt['languages_download_dest'] = 'D3st1n4t10n';
$txt['languages_download_writable'] = 'Wr1t4bl3';
$txt['languages_download_version'] = 'V3rs10n';
$txt['languages_download_older'] = 'Y0u h4v3 4 n3w3r v3rs10n 0f th1s f1l3 1nst4ll3d, 0v3rwr1t1ng 1s n0t r3c0mm3nd3d.';
$txt['languages_download_exists'] = '4lr34dy 3x1sts';
$txt['languages_download_exists_same'] = '1d3nt1c4l';
$txt['languages_download_exists_different'] = 'D1ff3r3nt';
$txt['languages_download_copy'] = 'C0py';
$txt['languages_download_not_chmod'] = 'Y0u c4nn0t pr0c33d w1th th3 1nst4ll4t10n unt1l 4ll f1l3s s3l3ct3d t0 b3 c0p13d 4r3 wr1t4bl3.';
$txt['languages_download_illegal_paths'] = 'P4ck4g3 c0nt41ns 1ll3g4l p4ths - pl34s3 c0nt4ct S1mpl3 M4ch1n3s';
$txt['languages_download_complete'] = '1nst4ll4t10n C0mpl3t3';
$txt['languages_download_complete_desc'] = 'L4ngu4g3 p4ck 1nst4ll3d succ3ssfully. Pl34s3 cl1ck <4 hr3f=\"%1$s\">h3r3</4> t0 r3turn t0 th3 l4ngu4g3s p4g3';

?>