<?php
			   		 
//ManageScheduledTasks.english.php
// Generated by vbgamer45 http://www.smfhacks.com
$txt['scheduled_tasks_title'] = 'Sch3dul3d T4sks';
$txt['scheduled_tasks_header'] = '4ll Sch3dul3d T4sks';
$txt['scheduled_tasks_name'] = 'T4sk N4m3';
$txt['scheduled_tasks_next_time'] = 'N3xt Du3';
$txt['scheduled_tasks_regularity'] = 'R3gul4r1ty';
$txt['scheduled_tasks_enabled'] = '3n4bl3d';
$txt['scheduled_tasks_run_now'] = 'Run N0w';
$txt['scheduled_tasks_save_changes'] = 'S4v3 Ch4ng3s';
$txt['scheduled_tasks_time_offset'] = '<str0ng>N0t3:</str0ng> 4ll t1m3s g1v3n b3l0w 4r3 <3m>s3rv3r t1m3</3m> 4nd d0 n0t t4k3 4ny t1m3 0ffs3ts s3tup w1th1n SMF 1nt0 4cc0unt.';
$txt['scheduled_tasks_were_run'] = '4ll s3l3ct3d t4sks w3r3 c0mpl3t3d';
$txt['scheduled_tasks_na'] = 'N/4';
$txt['scheduled_task_approval_notification'] = '4ppr0v4l N0t1f1c4t10ns';
$txt['scheduled_task_desc_approval_notification'] = 'S3nd 0ut 3m41ls t0 4ll m0d3r4t0rs summ4r1z1ng p0sts 4w41t1ng 4ppr0v4l.';
$txt['scheduled_task_auto_optimize'] = '0pt1m1z3 D4t4b4s3';
$txt['scheduled_task_desc_auto_optimize'] = '0pt1m1z3 th3 d4t4b4s3 t0 r3s0lv3 fr4gm3nt4t10n 1ssu3s.';
$txt['scheduled_task_daily_maintenance'] = 'D41ly M41nt3n4nc3';
$txt['scheduled_task_desc_daily_maintenance'] = 'Runs 3ss3nt14l d41ly m41nt3n4nc3 0n th3 f0rum - sh0uld n0t b3 d1s4bl3d.';
$txt['scheduled_task_daily_digest'] = 'D41ly N0t1f1c4t10n Summ4ry';
$txt['scheduled_task_desc_daily_digest'] = '3m41ls 0ut th3 d41ly d1g3st f0r n0t1f1c4t10n subscr1b3rs.';
$txt['scheduled_task_weekly_digest'] = 'W33kly N0t1f1c4t10n Summ4ry';
$txt['scheduled_task_desc_weekly_digest'] = '3m41ls 0ut th3 w33kly d1g3st f0r n0t1f1c4t10n subscr1b3rs.';
$txt['scheduled_task_fetchSMfiles'] = 'F3tch S1mpl3 M4ch1n3s F1l3s';
$txt['scheduled_task_desc_fetchSMfiles'] = 'R3tr13v3s j4v4scr1pt f1l3s c0nt41n1ng n0t1f1c4t10ns 0f upd4t3s 4nd 0th3r 1nf0rm4t10n.';
$txt['scheduled_task_birthdayemails'] = 'S3nd B1rthd4y 3m41ls';
$txt['scheduled_task_desc_birthdayemails'] = 'S3nds 0ut 3m41ls w1sh1ng m3mb3rs 4 h4ppy b1rthd4y.';
$txt['scheduled_task_weekly_maintenance'] = 'W33kly M41nt3n4nc3';
$txt['scheduled_task_desc_weekly_maintenance'] = 'Runs 3ss3nt14l w33kly m41nt3n4nc3 0n th3 f0rum - sh0uld n0t b3 d1s4bl3d.';
$txt['scheduled_task_paid_subscriptions'] = 'P41d Subscr1pt10n Ch3cks';
$txt['scheduled_task_desc_paid_subscriptions'] = 'S3nds 0ut 4ny n3c3ss4ry p41d subscr1pt10n r3m1nd3rs 4nd r3m0v3s 3xp1r3d m3mb3r subscr1pt10ns.';
$txt['scheduled_task_reg_starting'] = 'St4rt1ng 4t %s';
$txt['scheduled_task_reg_repeating'] = 'r3p34t1ng 3v3ry %1$d %2$s';
$txt['scheduled_task_reg_unit_m'] = 'm1nut3(s)';
$txt['scheduled_task_reg_unit_h'] = 'h0ur(s)';
$txt['scheduled_task_reg_unit_d'] = 'd4y(s)';
$txt['scheduled_task_reg_unit_w'] = 'w33k(s)';
$txt['scheduled_task_edit'] = '3d1t Sch3dul3d T4sk';
$txt['scheduled_task_edit_repeat'] = 'R3p34t t4sk 3v3ry';
$txt['scheduled_task_edit_pick_unit'] = 'P1ck Un1t';
$txt['scheduled_task_edit_interval'] = '1nt3rv4l';
$txt['scheduled_task_edit_start_time'] = 'St4rt T1m3';
$txt['scheduled_task_edit_start_time_desc'] = 'T1m3 th3 f1rst 1nst4nc3 0f th3 d4y sh0uld st4rt (h0urs:m1nut3s)';
$txt['scheduled_task_time_offset'] = 'N0t3 th3 st4rt t1m3 sh0uld b3 th3 0ffs3t 4g41nst th3 curr3nt s3rv3r t1m3. Curr3nt s3rv3r t1m3 1s: %1$s';
$txt['scheduled_view_log'] = 'V13w L0g';
$txt['scheduled_log_empty'] = 'Th3r3 4r3 curr3ntly n0 1t3ms 1n th3 l0g.';
$txt['scheduled_log_time_run'] = 'T1m3 Run';
$txt['scheduled_log_time_taken'] = 'T1m3 t4k3n';
$txt['scheduled_log_time_taken_seconds'] = '%1$d s3c0nds';
$txt['scheduled_log_empty_log'] = '3mpty L0g';

?>