<?php
			   		 
//ManageMail.english.php
// Generated by vbgamer45 http://www.smfhacks.com
$txt['mailqueue_desc'] = 'Fr0m th1s p4g3 y0u c4n c0nf1gur3 y0ur m41l s3tt1ngs, 4s w3ll 4s v13w1ng 4nd 4dm1n1str4t1ng th3 curr3nt m41l qu3u3 1f 1t 1s 3n4bl3d.';
$txt['mail_type'] = 'M41l typ3';
$txt['mail_type_default'] = '(PHP d3f4ult)';
$txt['smtp_host'] = 'SMTP s3rv3r';
$txt['smtp_port'] = 'SMTP p0rt';
$txt['smtp_username'] = 'SMTP us3rn4m3';
$txt['smtp_password'] = 'SMTP p4ssw0rd';
$txt['mail_queue'] = '3n4bl3 M41l Qu3u3';
$txt['mail_limit'] = 'M4x1mum 3m41ls t0 s3nd p3r m1nut3';
$txt['mail_limit_desc'] = '(S3t t0 0 t0 d1s4bl3)';
$txt['mail_quantity'] = 'M4x1mum 4m0unt 0f 3m41ls t0 s3nd p3r p4g3 l04d';
$txt['mailqueue_stats'] = 'M41l Qu3u3 St4t1st1cs';
$txt['mailqueue_oldest'] = '0ld3st M41l';
$txt['mailqueue_oldest_not_available'] = 'N/4';
$txt['mailqueue_size'] = 'Qu3u3 L3ngth';
$txt['mailqueue_age'] = '4g3';
$txt['mailqueue_priority'] = 'Pr10r1ty';
$txt['mailqueue_recipient'] = 'R3c1p13nt';
$txt['mailqueue_subject'] = 'Subj3ct';
$txt['mailqueue_clear_list'] = 'S3nd M41l Qu3u3 N0w';
$txt['mailqueue_no_items'] = 'Th3 m41l qu3u3 1s curr3ntly 3mpty';
$txt['mailqueue_clear_list_warning'] = '4r3 y0u sur3 y0u w1sh t0 s3nd th3 wh0l3 m41l qu3u3 n0w? Th1s w1ll 0v3rr1d3 4ny l1m1ts y0u h4v3 s3t.';
$txt['mq_day'] = '%1.1f D4y';
$txt['mq_days'] = '%1.1f D4ys';
$txt['mq_hour'] = '%1.1f H0ur';
$txt['mq_hours'] = '%1.1f H0urs';
$txt['mq_minute'] = '%d M1nut3';
$txt['mq_minutes'] = '%d M1nut3s';
$txt['mq_second'] = '%d S3c0nd';
$txt['mq_seconds'] = '%d S3c0nds';
$txt['mq_mpriority_5'] = 'V3ry L0w';
$txt['mq_mpriority_4'] = 'L0w';
$txt['mq_mpriority_3'] = 'N0rm4l';
$txt['mq_mpriority_2'] = 'H1gh';
$txt['mq_mpriority_1'] = 'V3ry H1gh';
$txt['birthday_email'] = 'B1rthd4y M3ss4g3 t0 us3';
$txt['birthday_body'] = '3m41l B0dy';
$txt['birthday_subject'] = '3m41l Subj3ct';

?>