<?php
			   		 
//Settings.english.php
// Generated by vbgamer45 http://www.smfhacks.com
$txt['theme_thumbnail_href'] = '/thumbn41l.g1f';
$txt['theme_description'] = 'Th3 d3f4ult th3m3 fr0m S1mpl3 M4ch1n3s.<br /><br />Th4nks g0 t0 Bl0c 4nd th3 d3s1gn t34m.';

?>