<?php
			   		 
//Stats.english.php
// Generated by vbgamer45 http://www.smfhacks.com
$txt['most_online'] = 'M0st 0nl1n3';
$txt['stats_center'] = 'St4t1st1cs C3nt3r';
$txt['general_stats'] = 'G3n3r4l St4t1st1cs';
$txt['top_posters'] = 'T0p 10 P0st3rs';
$txt['top_boards'] = 'T0p 10 B04rds';
$txt['forum_history'] = 'F0rum H1st0ry (us1ng f0rum t1m3 0ffs3t)';
$txt['stats_date'] = 'D4t3 (yyyy/mm/dd)';
$txt['stats_new_topics'] = 'N3w T0p1cs';
$txt['stats_new_posts'] = 'N3w P0sts';
$txt['stats_new_members'] = 'N3w M3mb3rs';
$txt['page_views'] = 'P4g3 v13ws';
$txt['top_topics_replies'] = 'T0p 10 T0p1cs (by R3pl13s)';
$txt['top_topics_views'] = 'T0p 10 T0p1cs (by V13ws)';
$txt['yearly_summary'] = 'Y34rly Summ4ry';
$txt['smf_stats_14'] = 'M0st 0nl1n3';
$txt['top_starters'] = 'T0p T0p1c St4rt3rs';
$txt['most_time_online'] = 'M0st T1m3 0nl1n3';
$txt['best_karma'] = 'B3st K4rm4';
$txt['worst_karma'] = 'W0rst K4rm4';
$txt['stats_more_detailed'] = 'm0r3 d3t41l3d &r4qu0;';
$txt['average_members'] = '4v3r4g3 r3g1str4t10ns p3r d4y';
$txt['average_posts'] = '4v3r4g3 p0sts p3r d4y';
$txt['average_topics'] = '4v3r4g3 t0p1cs p3r d4y';
$txt['average_online'] = '4v3r4g3 0nl1n3 p3r d4y';
$txt['users_online'] = 'Us3rs 0nl1n3';
$txt['gender_ratio'] = 'M4l3 t0 F3m4l3 R4t10';
$txt['users_online_today'] = '0nl1n3 T0d4y';
$txt['num_hits'] = 'T0t4l p4g3 v13ws';
$txt['average_hits'] = '4v3r4g3 p4g3 v13ws p3r d4y';
$txt['ssi_comment'] = 'c0mm3nt';
$txt['ssi_comments'] = 'c0mm3nts';
$txt['ssi_write_comment'] = 'Wr1t3 C0mm3nt';
$txt['ssi_no_guests'] = 'Y0u c4nn0t sp3c1fy 4 b04rd th4t d03sn\'t 4ll0w gu3sts.  Pl34s3 ch3ck th3 b04rd 1D b3f0r3 try1ng 4g41n.';
$txt['xml_rss_desc'] = 'L1v3 1nf0rm4t10n fr0m ';

?>