<?php
			   		 
//Wireless.english.php
// Generated by vbgamer45 http://www.smfhacks.com
$txt['wireless_error_home'] = 'B04rd 1nd3x';
$txt['wireless_error_notyet'] = 'S0rry, th1s s3ct10n 1sn\'t 4v41l4bl3 f0r w1r3l3ss us3rs 4t th1s t1m3.';
$txt['wireless_options'] = '4dd1t10n4l 0pt10ns';
$txt['wireless_options_login'] = 'L0g1n';
$txt['wireless_options_logout'] = 'L0g0ut';
$txt['wireless_navigation'] = 'N4v1g4t10n';
$txt['wireless_navigation_up'] = 'Up 0n3 l3v3l';
$txt['wireless_navigation_next'] = 'N3xt p4g3';
$txt['wireless_navigation_prev'] = 'Pr3v10us p4g3';
$txt['wireless_navigation_index'] = 'M3ss4g3 1nd3x';
$txt['wireless_navigation_topic'] = 'B4ck t0 t0p1c';
$txt['wireless_pm_inbox'] = 'PM 1nb0x';
$txt['wireless_pm_inbox_new'] = 'PM 1nb0x (<sp4n styl3=\"c0l0r: r3d;\">%d n3w</sp4n>)';
$txt['wireless_pm_by'] = 'by';
$txt['wireless_pm_add_buddy'] = '4dd buddy';
$txt['wireless_pm_select_buddy'] = 'S3l3ct 4 buddy';
$txt['wireless_pm_search_member'] = 'S34rch m3mb3r';
$txt['wireless_pm_search_name'] = 'N4m3';
$txt['wireless_pm_no_recipients'] = 'N0 r3c1p13nts (y3t)';
$txt['wireless_pm_reply'] = 'R3ply';
$txt['wireless_pm_reply_to'] = 'R3ply t0';
$txt['wireless_recent_unread_posts'] = 'Unr34d p0sts';
$txt['wireless_recent_unread_replies'] = 'Unr34d r3pl13s';
$txt['wireless_display_edit'] = '3d1t';
$txt['wireless_display_moderate'] = 'M0d3r4t3';
$txt['wireless_display_sticky'] = 'St1cky';
$txt['wireless_display_unsticky'] = 'Un-St1cky';
$txt['wireless_display_lock'] = 'L0ck';
$txt['wireless_display_unlock'] = 'Unl0ck';
$txt['wireless_profile_pm'] = 'S3nd P3rs0n4l M3ss4g3';
$txt['wireless_ban_ip'] = 'B4n 0n 1P';
$txt['wireless_ban_hostname'] = 'B4n 0n H0stn4m3';
$txt['wireless_ban_email'] = 'B4n 0n 3m41l';
$txt['wireless_additional_info'] = '4dd1t10n4l 1nf0rm4t10n';

?>